### ISSUE TITLE
Update style naming pattern to help designer work faster in figma

### ISSUE THREAD

**Issue by codecycleteam** [material-foundation/material-theme-builder#1]
Hello

**Problem**
Current naming convention are good but it is not helping designer to recognise which style is for what.
See the existing pattern of style names in figma in below image in which it will be harder to recognise style name and use. 
<img width="215" alt="Image01" src="https://user-images.githubusercontent.com/84431724/139402851-22842315-284d-4771-9498-7d9c7632a57b.png">

Below view will not help because it will have long scroll due to both theme light and dark are inside one theme.
<img width="215" alt="Image03" src="https://user-images.githubusercontent.com/84431724/139403837-4839b57e-2583-4932-937b-8110baccfb6a.png">

**Solutions**
01 - Change naming convention to support below image format
<img width="216" alt="Image02" src="https://user-images.githubusercontent.com/84431724/139403064-58ccf2e2-6d73-499b-8569-9f42642c8cea.png">

02 - Add support in figma plugin to create & maintain light theme and dark theme separately.
As shown in below image.
<img width="229" alt="Image 04" src="https://user-images.githubusercontent.com/84431724/139404839-564a7492-6eea-4381-a495-fdbac7848f0f.png">

Awaiting response from team. Thank You.

**Comment by rodydavis** [comment]
With the latest version of Figma it should show the names a lot easier now. Please reopen if it is still an issue, but the names are needed for metadata.
