### ISSUE TITLE
Prevent styles from updating automatically 

### ISSUE THREAD

**Issue by MrBeardedGuy** [material-foundation/material-theme-builder#103]
0. Launch Figma and the Material Theme plugin
1. Open an extremely big file with 5+ styles and complex components
2. Enable the Plugin
3. Observe Figma slows down tremendously because styles are applied immediately
4. The situation gets worse if the user tweaks few options (i.e adds an image and then switched from "Wallpaper" to "Content" mode)

DESIRED BEHAVIOUR
Add a button to manually trigger the styles updates so the user can select all the appropriate options.

**Comment by margeeta** [comment]
Thanks for your feedback, we have some related updates planned! Keep an eye out.
