### ISSUE TITLE
Latest Material Theme Builder update for Figma broke the plugin 

### ISSUE THREAD

**Issue by LPirro** [material-foundation/material-theme-builder#104]
Hello,

As some people reported on the [Official Page on Figma](https://www.figma.com/community/plugin/1034969338659738588/Material-Theme-Builder) the plugin is broken after the last update. I'm not being able to use it, swapping light/dark for example, does not work properly, and also the UI looks really weird.

Just wanted to open an issue to let you know. Please help the community with this because, in its current state, the plugin is not usable anymore.

For any additional information that could help investigate this just let me know.

Thank you.

**Comment by margeeta** [comment]
Hi, thank you filing the issue!

The latest update was needed to fix some long standing bugs like correcting colors from being overwritten when opening the plugin along with addressing performance. This meant updating some token syntax along the way. 

That said, light/dark swap should work still even with previous themes (unless it's a very old theme). It may take a second or two to actually swap them. 

You may have to generate a new theme to get key colors to register and show up, without doing so will register as No Core Colors Found. 

Do you mind providing any screenshots? We will be doing some follow updates to address UI bugs along with troubleshooting notes.

**Comment by LPirro** [comment]
@margeeta Sure. It seems that something is broken with the tokens. I also tried with a brand new project. It just doesn't change the colours for components from a library (like Material Design Kit). Components like Buttons, Navbars, Chips, etc.
![Screenshot 2023-01-20 at 09 47 00](https://user-images.githubusercontent.com/3328096/213654244-0b8ab46a-4660-4882-941f-1e3afcb8bd0d.png)

It's really sad because I cannot design anymore like this :(

**Comment by margeeta** [comment]
We will be making a design kit update to align tokens. I did have success swapping components though, but it did take a couple tries with Swap.

**Comment by LPirro** [comment]
@margeeta Thanks for addressing this. If I can help somehow just let me know.

Also, more people are commenting on Figma Page that they have issues with the plugin: https://www.figma.com/community/plugin/1034969338659738588/Material-Theme-Builder

**Comment by LPirro** [comment]
@margeeta any update on this?

**Comment by margeeta** [comment]
Design kit to be updated this week to reflect latest color updates!
