### ISSUE TITLE
BUG REPORT : MATERIAL THEME BUILDER COLOR PICKER

### ISSUE THREAD

**Issue by hoangdinh3868** [material-foundation/material-theme-builder#105]
1-Launch Figma on desktop and the Material Theme plugin
2-Click changing color for a neutral color
3-Plugin does not have a small table for a color picker
4- Color Picker appears on the sample does not match an outcome color? (green color; instead of grey color)

**Screenshots**
![image](https://user-images.githubusercontent.com/123075507/213461989-42563bdb-a442-463d-8c2b-8effa69faf9f.png)

**Desktop (please complete the following information):**
 - OS: HP Spectre
 - Browser: Chrome
 - Version: 109.0.5414.75 (Official Build) (64-bit)

**Comment by margeeta** [comment]
Fixed with latest releases.
