### ISSUE TITLE
Update theme colors only if I add a new theme

### ISSUE THREAD

**Issue by lsalehar** [material-foundation/material-theme-builder#106]
It's really annoying that the plugin changes colors of the theme when I change the theme from dynamic to custom and everytime I open the plugin.

Please:
1. Change existing theme only when I change the color manually
2. Don't change existing theme if I switch from dynamic to custom (display currently defined colors) - It's great to customize a theme from a defined source color that was generated dynamically
3. Keep the colors if I add a theme
4. Change colors only if I switch themes.

**Comment by margeeta** [comment]
Thanks @lsalehar, we have to reset between the two states for plugin performance currently. 

But, in your workflow, would you prefer customization and dynamic together or to remain separate, as it is now?

**Comment by lsalehar** [comment]
Hi @margeeta, thank you for the reply. Can you please elaborate on your question a bit further? I'm afraid I don't understand exactly what you're asking me.

**Comment by margeeta** [comment]
Now should only update when color has been changed, and applied. 

We sadly can't keep the dynamically generated theme between the two states, but have some planned future work to resolve this! 
But primary in custom does act in the same way source color does in dynamic, if you'd like to generate an entire scheme from one source color.
