### ISSUE TITLE
BUG: Settings are not saved

### ISSUE THREAD

**Issue by lsalehar** [material-foundation/material-theme-builder#107]
If you enable:
- Harmonize extedned colors
- Generate State Layers
- Generate Text Styles

the settings are not saved when clickin back button (there is no save button):

Before going back:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/4621819/213911108-207d7c43-4f31-4d5b-b039-503d14ca05c7.png">

After opening settings again:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/4621819/213911125-a3e3e2bd-ec2b-4491-a5e0-58cb874cf075.png">

**Comment by c5inco** [comment]
I see a similar thing as well, and also find it unpredictable to know how the settings are related to each other (in video you see sometimes checking one box checks all other boxes):

https://user-images.githubusercontent.com/1253402/222058604-47963b80-4774-4bf5-b9f1-0588b2cf4038.mov

**Comment by margeeta** [comment]
Fixed!
