### ISSUE TITLE
Material Theme Builder for PenPot

### ISSUE THREAD

**Issue by keunes** [material-foundation/material-theme-builder#108]
**Is your feature request related to a problem? Please describe.**
For our open source project we use Figma-competitor PenPot. Currently I used the web theme builder and manually created all tokens as colour assets in Penpot. It was a bit of a lengthy exercise.

**Describe the solution you'd like**
Not sure if possible, as I suppose there's some colour calculations going on in the background. But it'd be great if you could (work with the folks behind PenPot to) provide a Material Theme Builder for PenPot.

**Describe alternatives you've considered**
Alternatively it'd be cool to have the ability to download a PenPot Library with the colour palette as created in the MTB.

**Additional context**
PenpPot is an awesome Figma-competitor, and Open Source at that. Check it out on https://penpot.app/

**Comment by margeeta** [comment]
We are always listening to what platforms our community would like us to support. We'll make a note and keep PenPot in mind!

**Comment by candidexmedia** [comment]
+1 for Penpot!
