### ISSUE TITLE
Button to swap secondary & tertiary colour

### ISSUE THREAD

**Issue by keunes** [material-foundation/material-theme-builder#109]
**Is your feature request related to a problem? Please describe.**
I'm making mock-ups and hesitating which colour to use as 'secondary' and which as 'tertiary' colour. Switching the Secondary & Tertiary colours (in order to see them in the example components) is a bit of a copy-and-paste pain.

**Describe the solution you'd like**
A simple button (e.g. with down/up arrows) to swap/switch the colours.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by margeeta** [comment]
Thank you for the feedback @keunes 
Would you want to do the same between primary? If so, would you still expect primary to act as the source color for the rest of the color scheme?

**Comment by margeeta** [comment]
added to feature requests log, closing issue
