### ISSUE TITLE
Plugin UI seems to have a missing font

### ISSUE THREAD

**Issue by elv-heath** [material-foundation/material-theme-builder#11]
**Describe the bug**
The fonts used in the UI seem to be off.

**To Reproduce**
Launch the plugin

**Screenshots**
<img width="372" alt="Screen Shot 2021-11-02 at 9 51 38 AM" src="https://user-images.githubusercontent.com/80486506/139860481-f0e5f602-d299-401e-aa8e-8629df76071b.png">

**Desktop (please complete the following information):**
macOS Big Sur

**Comment by whatsthedealwith** [comment]
same thing happening on my windows 10 machine

**Comment by rodydavis** [comment]
Can you test with the latest build? I think I was able to resolve the issue with the font import.

**Comment by rodydavis** [comment]
I was able to find the issue but it should be resolved now! Please reopen if it is still happening to you
