### ISSUE TITLE
Margin missing between Mock-ups & Components

### ISSUE THREAD

**Issue by keunes** [material-foundation/material-theme-builder#111]
**Describe the bug**

**To Reproduce**
1. Go to https://m3.material.io/theme-builder

**Expected behavior**
There's some spacing between the mock-ups and the components.

**Screenshots**
![image](https://user-images.githubusercontent.com/11229646/213940994-8504aec1-a531-4b27-be18-abb37478262a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium

**Additional context**
None

**Comment by margeeta** [comment]
Thanks, bug filed to update
