### ISSUE TITLE
Certain settings cannot be applied

### ISSUE THREAD

**Issue by sweetdrumster** [material-foundation/material-theme-builder#112]
After recent update the plugin doesn't generate Android Styles, State Layers and Text Styles. Corresponding checkboxes in Settings and Resources do not cause any effect and being automatically deselected.
I'm using the latest Figma version: Figma Desktop App version 116.5.18 on MacOS 13.1 (22C65).

**Comment by bracketsberlin** [comment]
Same problem here.
