### ISSUE TITLE
Vibrance Options

### ISSUE THREAD

**Issue by blok5025** [material-foundation/material-theme-builder#114]
**Is your feature request related to a problem? Please describe.**
Although beautiful, the colour schemes that are generated are blend. It might be suitable for many designs but some of the designs require more vibrant colours. For that reason, there should be an option to increase the overall vibrance of the scheme.

**Describe the solution you'd like**
A slider will be a nice option. While I am not an expert in colour ways, other more suitable options such as toggles can be used in case a slider is not appropriate.

**Describe alternatives you've considered**
See above.

**Comment by margeeta** [comment]
Thank you for the feedback and keep an eye out for updates to the color algorithm to address vibrancy!
