### ISSUE TITLE
There is no "Export" button for Dynamic color scheme

### ISSUE THREAD

**Issue by irinache** [material-foundation/material-theme-builder#116]
There is no "Export" button for Dynamic color scheme.

1. Launch Figma on desktop and the Material Theme plugin
2. Click on Dynamic tab.

Expected behavior:
There is an "Export" button at the bottom of the window, as on the "Custom tab"

**Screenshots**
This is an example of how it should be:
![image](https://user-images.githubusercontent.com/39464532/216010344-9c7fe106-f009-471b-8124-040be2e3ffee.png)

This is an example of what I get:
![image](https://user-images.githubusercontent.com/39464532/216010638-467fe819-5911-43e0-badb-6d81c9646066.png)

**Comment by margeeta** [comment]
Hi! Currently dynamic is for previewing purposes only, how designs could look using wallpaper or content colors. Exporting is available for custom themes. Please keep a look out for future updates, as this may change!
