### ISSUE TITLE
M3 template and M3 theme builder pluging for Figma

### ISSUE THREAD

**Issue by maximus-ww2** [material-foundation/material-theme-builder#118]
When using M3 Template and M3 Theme builder pluging in Figma (Custom Section colors of the plugin): 
-The Color Guidance frame (material theme) is not displaying the Extended Colors from the plugin
-The Color Guidance frame (material theme) is not updating compleatly: neutral color is not displayed
![Capture-Figma](https://user-images.githubusercontent.com/17593917/216269855-a9fb1659-66b2-4327-b0d0-d28782c0bae9.JPG)

**Comment by andersonuk** [comment]
Would be just nice to generate everything here and then import it to Figma.
https://m3.material.io/theme-builder#/custom 

In their website, the changes are just fast.

I hope they address this issue soon. Hard to find a good DS as this one
