### ISSUE TITLE
Secondary colors don't change on the design files while the color on plugin interface changed. 

### ISSUE THREAD

**Issue by Aliiiceee** [material-foundation/material-theme-builder#119]
Secondary colors don't change on the design files while the color on the material theme builder plugin interface changed.

**Comment by lydia680** [comment]
Same here

**Comment by margeeta** [comment]
Hi, Can you please provide more info and steps, along with screenshots? Thank you.

**Comment by margeeta** [comment]
The M3 color system just updated Surfaces and released new fixed accent roles. 
Surfaces are no longer computed as overlays and now based on tonal values! 
More here: https://m3.material.io/styles/color/the-color-system/color-roles#0abbf8b7-61e1-49ee-9f97-4967beb1e4fe

Fixed accents are a new color group that stays the same across light and dark theme. 
Fixed accent: https://m3.material.io/styles/color/the-color-system/color-roles#232e7275-6ef2-4b93-afa6-c5f76e378ced

**Comment by lucaben** [comment]
Thanks @margeeta. Would you recommend to wait a few days for the changes to the surface colours to be reflected in Figma, or can it also be done later? 
It looks to me like there isn't a distinction anymore between neutral grey colours and surface colours, which would then simplify things a bit. Did I get it right?
