### ISSUE TITLE
Settings & Resources do not persist option changes

### ISSUE THREAD

**Issue by kirill-develops** [material-foundation/material-theme-builder#128]
When I click the harmonize extended colours or generate state layers, and generate text styles, these options do not remain clicked when I check the settings afterwards. Great tool otherwise.

would love an integration with MUI, thanks team

**Comment by margeeta** [comment]
Thank you! 
We are working on resolving an issue with persistent settings, and should be out in an upcoming update. 

For MUI integration request, are you looking for a React export? MUI is not a Google library.

**Comment by kirill-develops** [comment]
It's good to hear that an update is coming, and Google is on top of it! I appreciate the system and its ability to improve app and web development cohesiveness.

I apologize for not knowing that MUI was developed by a third party. I really like the colour palette and would love to see an option to customize an MUI theme to incorporate all the different layers of the Material Design Palette.

Thank you for your hard work regardless!

**Comment by margeeta** [comment]
Settings now persist :)
