### ISSUE TITLE
Android tokens do not update automatically

### ISSUE THREAD

**Issue by PrattiDev** [material-foundation/material-theme-builder#13]
**Describe the bug**
After Android Schemes are generated, the values within are static and do not update when picking a color or a wallpaper from the plugin window — instead, they remain intact unless the user manually generates another Android Scheme.

**To Reproduce**
1. Generate Android Schemes from the plugin options in Figma.
2. Try changing the color or wallpaper selection.
3. The Android colors will not update.

![easRbuFeBX](https://user-images.githubusercontent.com/17130024/142934401-fcaf019f-edb2-420b-8833-75675e0be618.gif)

**Expected behavior**
The Android colors are supposed to update alongside everything else.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 92.0.4515.131

**Comment by rodydavis** [comment]
Can you test with the latest?

**Comment by PrattiDev** [comment]
> Can you test with the latest?

Tried it just now on the browser and the Windows app (stable), but unfortunately, Android tokens are still not updating automatically. The missing font issue that was apparently fixed in this build is also not fixed for me. I did get the color tooltips, so that means it's not an older version of the plugin.

**Comment by tbsbdr** [comment]
+1 same issue here on MacOS

**Comment by rodydavis** [comment]
I will continue to test!
