### ISSUE TITLE
Extended colours

### ISSUE THREAD

**Issue by aunpixelfield** [material-foundation/material-theme-builder#130]
Extended colour that I add do not get saved, and do not get added to the colour styles.

**Comment by aunpixelfield** [comment]
Above may be related to 'Setting & Resources' not saving my preferences. No matter how many times I check "Harmonize extended colors", it then uncheck when I click settings again.

<img width="350" alt="Screenshot 2023-03-03 at 14 02 01" src="https://user-images.githubusercontent.com/126887736/222739355-21798cc6-cca0-4d61-a9bd-bc9d994200d7.png">


<img width="358" alt="Screenshot 2023-03-03 at 14 03 12" src="https://user-images.githubusercontent.com/126887736/222739647-499706c2-21c0-472d-bafd-acf5d575a443.png">

**Comment by margeeta** [comment]
Extended colors are added into Figma styles. Settings now persist.
