### ISSUE TITLE
Extended colours pallet / Fonts

### ISSUE THREAD

**Issue by andersonuk** [material-foundation/material-theme-builder#131]
1 - Extended colours pallet are not being generated. The styles are just fine but I don't see the scheme on Figma
2 - Fonts: All the time when I change colours, the fonts are rested to Roboto.

Thank you!

**Comment by margeeta** [comment]
Thanks! 
We've currently removed schematic generation, extended colors are still in the styles though!

For #2, make sure 'Generate Text Styles' is not checked within settings, as this will update text properties.
