### ISSUE TITLE
Imported theme doesn't show in select list and no color diagram is being created

### ISSUE THREAD

**Issue by bracketsberlin** [material-foundation/material-theme-builder#135]
**Describe the bug**
JSON-imported themes don't instantly appear in the select list. And no color diagram is created.

**To Reproduce**
1. Open Theme Builder Plugin
2. Choose from select list "Import theme file (JSON)", the theme is being imported and styles are created. No color diagram is being generated (settings show option to be activated). And I also can't select my imported theme in the select list. It appears that the imported theme only overwrites the colors in the color pickers but it doesn't have an effect on the currently selected theme.

**Expected behavior**
1. User clicks on "Import theme file (JSON)"
2. Finds imported theme with it's name in select list --> theme only shows after opening and closing plugin window
3. A color diagram is being generated

**Desktop:**
 - OS: macOS 12.2
 - Browser: Chrome
 - Version: 111.0.5563.64

**Comment by margeeta** [comment]
There must be an existing theme with the same name as the JSON theme, Import JSON updates the values. 
Meaning a new scheme will not be generated, but the existing styles and schematic will update.

**Comment by bracketsberlin** [comment]
@margeeta thanks. Then I'd consider it rather a feature-request if multiple users would expect this feature to work like that.

**Comment by margeeta** [comment]
Sure! Will close this ticket, and will note as feature request :) 
Import button to be renamed for now.
