### ISSUE TITLE
CSS Export missing some tokens that are referenced in typography.module.css

### ISSUE THREAD

**Issue by nmunday** [material-foundation/material-theme-builder#136]
**Describe the bug**
The typography.module.css file references "--md-sys-typescale-body-medium-text-transform" and "--md-sys-typescale-body-medium-text-decoration" which do not seem to be declared anywhere. 

**To Reproduce**
Export to CSS
In typography.module.css text-transform and text-decoration reference variables that are not declared.

**Expected behavior**
All variable references should be declared.

**Screenshots**
![image](https://user-images.githubusercontent.com/7116951/225073960-b27468c1-2b8b-427b-874a-5a6e713e8466.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Any

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android
 - Browser Chrome
 - Version Any

**Additional context**

**Comment by jwill** [comment]
Thanks for the report.

At the present time, we're no longer generating typography in the versions under active development, neither Figma nor the web version at https://material-foundation.github.io/material-theme-builder/
