### ISSUE TITLE
Download is not working

### ISSUE THREAD

**Issue by lululeon** [material-foundation/material-theme-builder#137]
**Describe the bug**
Downloading custom design on material theme builder not working: https://m3.material.io/theme-builder#/custom

**To Reproduce**
1. Go to [the material theme builder](https://m3.material.io/theme-builder#/custom)
2. Click on the **export** button at top right and select **Jetpack Compose Theme**
3. Open the inspector and look at the console. You will find the error: 
```
app.js?version=1670027719620561:13291 Uncaught (in promise) TypeError: module$exports$google3$third_party$javascript$typings$jszip$index is not a constructor
    at module$exports$google3$ux$material$theme_builder$core$exporters$compose$ComposeExporter.download (app.js?version=1670027719620561:13291:794)
```
5. No files/assets are downloaded.

**Expected behavior**
Expected files/assets to be downloaded

**Screenshots**
![image](https://user-images.githubusercontent.com/6601801/225697810-09a1b762-60cf-43cc-ab3c-bb8ee4f39f3f.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Version 111.0.5563.64 (Official Build) (arm64)
 
**Smartphone (please complete the following information):**

**Additional context**

**Comment by margeeta** [comment]
Hi! We recently released a new build, can you try reloading and trying again. This issue seems to be random and usually resolved with refreshing. Thanks!

**Comment by lululeon** [comment]
Ya it works great! I forgot to circle back and close this; closing now. Must've been something intermittent!
