### ISSUE TITLE
Material Theme Builder - infinite save (completely unusable)

### ISSUE THREAD

**Issue by viessg** [material-foundation/material-theme-builder#138]
Material Theme Builder can't be used on my chrome/figma as it infinitely saves 
![GoogleMaterialThemeBuilder_bug](https://user-images.githubusercontent.com/79990395/225866930-cd45994b-04a9-4cc0-a224-f31fa0eceb8e.jpg)

**Comment by BriteGirl** [comment]
That happens to me too. I copied Material 3 Design Kit but when I try to customize colors via  Theme Builder, it gets stuck on saving...

**Comment by PhoenixWings7** [comment]
That happens to me too. I copied Material 3 Design Kit but when I try to customize colors via Theme Builder, it gets stuck on saving...

**Comment by lucaben** [comment]
This plugin is almost impossible to use, as riddled with bugs as it is... primary colour used as a background for full buttons gets a different colour than the one chosen, state layers colours (used as background for outlined buttons) are not updated, infinite saving and the plugin not reflecting the current chosen palettes (has to be restarted after each change), and the documentation on how to use colours is almost non-existent and no rationale given on why there's so many palettes and styles.

**Comment by margeeta** [comment]
Thanks for the feedback. MTB has been updated. Figma may time out with large files, but it shouldn't get stuck on instances. 
For more on M3 color system check out https://m3.material.io/styles/color/the-color-system/key-colors-tones

**Comment by lucaben** [comment]
Thanks Margeeta. I guess the update to the Figma plugin would be pushed automatically, correct? I didn't see any notification. I've sent an email to the team, I think the documentation on how to use colours is insufficient. It's a very long list of styles with no rationale and examples given, and the tokens are inconsistent with the styles I see on the Figma MD 3 kit.
