### ISSUE TITLE
How to set or get Neutral-Variant color

### ISSUE THREAD

**Issue by Velkamhell97** [material-foundation/material-theme-builder#139]
I am learning how the new material 3 color system works, but I can't find the way to create the neutral-variant color, I see that this color changes when changing the primary color, but I also notice that it has some relation with the secondary color. I would like to know how or with what combination I can get this color to create other colors like surfaceVariant and outline without the constructor, since in the constructor I can't set this color so I guess this color is created based on the other colors of the theme.

Thank you very much.

**Comment by margeeta** [comment]
Hi, we recently added the Neutral Variant key color into the Figma plugin and will be adding into the website version as well.
