### ISSUE TITLE
Colour Dropper crashes Chrome

### ISSUE THREAD

**Issue by jkmckay** [material-foundation/material-theme-builder#14]
**Describe the bug**
Colour dropper tool crashes chrome when used outside of Chrome window.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://material-foundation.github.io/material-theme-builder/
2. Click on `custom` tab
3. Click on primary colour
4. Click the colour dropper tool
5. Use the colour dropper tool on any non-chrome window (e.g. terminal, slack, finder)
6. Observe Chrome crashes

**Expected behaviour**
Colour to be selected

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 96.0.4664.55

**Comment by FluorescentHallucinogen** [comment]
Material Theme Builder uses native browser built-in color picker. So it seems like a Chrome bug, not a Material Theme Builder bug.

Could you please type `data:text/html,<input type="color"/>` in the address bar and reproduce the problem?

Could you please also check on the latest [Chrome Canary](https://www.google.com/chrome/canary/) version?

If you can reproduce the bug in both cases, please open the issue on https://new.crbug.com.

**Comment by rodydavis** [comment]
Just tested with the latest and it doesn't seem to be crashing. 

Tested on Chrome `Version 96.0.4664.55`

**Comment by rodydavis** [comment]
Please open if it is still an issue
