### ISSUE TITLE
How to get the base color from the tone palette.

### ISSUE THREAD

**Issue by Velkamhell97** [material-foundation/material-theme-builder#140]
In some cases we have an existing design and we want to adapt the theme to the material guides. It is easy to identify the primary color of the design, but how can I get the base color used to create the tone palette, since the primary color for example is the base color with tone value of 40. Is it possible to get the base color from the tone palette?

Thank you very much.

**Comment by jingjingfan** [comment]
Hello - a follow up question to the generated tonal palette. Is there a way to have it also be exported as variables? i.e. primary10, blue10?
