### ISSUE TITLE
Plugin no longer creates `source` image color style

### ISSUE THREAD

**Issue by PrattiDev** [material-foundation/material-theme-builder#142]
**_In the latest update, the plugin will no longer generate the image color style that the theme color is based off of._**

This was important because it allowed you to sync Android components and system screens with your app mockups, if you needed to integrate them in some way.

Please bring it back!

Thank you.

**Comment by margeeta** [comment]
Thanks! I also miss and loved the image style feature, but it was causing issues. I'll record the request, hopefully we can bring it back one day!

**Comment by margeeta** [comment]
So… this is possible again, the plugin will convert non Material styles into a theme friendly style when selected and click the swap icon. 
![Screenshot 2023-12-20 at 2 36 26 PM](https://github.com/material-foundation/material-theme-builder/assets/10263978/bb59f0d8-faa0-4667-af10-23af65c7fa9c)

Also works with gradients :)

**Comment by PrattiDev** [comment]
@margeeta Could you explain a little how it works? The original post was about how the plugin would generate a wallpaper if one was used to generate dynamic colors. The plugin doesn't seem to actually do this.

**Comment by margeeta** [comment]
The plugin can create static styles and add to the generated theme to match the Material token formatting, so if you have an image you are using to generate colors from, it can still be included. More of a work around to the previous feature removal, to tie an image to a theme, I use it to add the source image into the themes.
