### ISSUE TITLE
Doesn't generate surface container colors

### ISSUE THREAD

**Issue by Garaba-PureCommit** [material-foundation/material-theme-builder#144]
Plugin doesn't generate surface container colors described here https://m3.material.io/styles/color/the-color-system/color-roles#8edc07d2-1579-4891-819f-b3a182704b19
How can I generate this colors for custom theme ?

**Comment by margeeta** [comment]
Hi,
 Expect a new update next week that will include the new surface roles and fixed accents! :)

**Comment by palexdev** [comment]
@margeeta 
2 weeks passed, but this seems to still be an issue
[https://m3.material.io/theme-builder#/custom](https://m3.material.io/theme-builder#/custom) doesn't generate the new surface tokens
Is it still an older version?

**Comment by margeeta** [comment]
@palexdev Yes, Figma has been updated, along with design kit. 
Web version will be updated soon!

**Comment by RequestPrivacy** [comment]
Any estimate on the update of the web version?

**Comment by kolyneh** [comment]
Hi, can you check this, Figma and Web doesn't export surface container colors for Android Views, Compose, Flutter.
It's only working for Json.

**Comment by qyzhaojinxi** [comment]
hi, surface container colors is still missing for android xml

**Comment by VitaliyBelyaev** [comment]
Hi! I also faced the problem that Figma Material Theme Builder Plugin doesn't add surface-container colors in xml for Android when exporting. In Figma those colors exist, also if exported as .json file surface-container colors exist there. 

As workaround, I create[ python script](https://gist.github.com/VitaliyBelyaev/bc1c95656396e26ddcda54bc40846310) that generates colors.xml and light/dark themes.xml from .json theme file exported from Figma plugin. Hope it helps someone!

**Comment by qyzhaojinxi** [comment]
@VitaliyBelyaev thanks, I will try it.

**Comment by qyzhaojinxi** [comment]
the text color on surface container is still missing. For example menu text color is black dark mode.
