### ISSUE TITLE
Material Theme Builder - Can not save Settings

### ISSUE THREAD

**Issue by MiaShi92** [material-foundation/material-theme-builder#145]
![image](https://user-images.githubusercontent.com/128781684/227443596-677df45b-29df-4d79-90b1-e0bc61c0df2a.png)

**Comment by margeeta** [comment]
Settings will now persist across sessions.

**Comment by MiaShi92** [comment]
Hi margeeta, 

Thank you for the assistance.  The settings can be saved currently.  
However, there's still a problem, that is the generated diagrams on the canvas are not related to the saved settings.
For example, I checked "Generate Text Style", "Generate Surface Styles", "Generate State Layers", there is no related diagram generated.  It seems that the generated diagrams are always these components in the following image.
![image](https://user-images.githubusercontent.com/128781684/230564684-031c472e-a34a-446a-b5c4-e4873e1433c2.png)
