### ISSUE TITLE
Theme switching doesn't work

### ISSUE THREAD

**Issue by PrattiDev** [material-foundation/material-theme-builder#146]
**Describe the bug**
Trying to switch from light to dark and vice-versa will only change a couple of tokens before giving up altogether.

**To Reproduce**
1. Open the official M3 UI Kit.
2. Open the plugin.
3. Select literally any component.
4. Click on the button that is the opposite of the current theme of the component.

**Expected behavior**
Components would switch themes, having their color styles replaced.

**Screenshots**
I attached a video.

**Device:**
 - Happens anywhere.

I sincerely hope there's a fix incoming - this is one of the main features of the plugin.

Thank you.

Example:

https://user-images.githubusercontent.com/17130024/227780153-4b1e0955-063c-45a0-a73c-388e9404b8b2.mp4

**Comment by margeeta** [comment]
New release is out and design kit will update soon, when using with the design kit, turn generate state-layers on. MTB should also swap styles within instances again.
