### ISSUE TITLE
Is there a way to generate typography for MD3 design to be used in Figma and the Material Tokens (dsp)?

### ISSUE THREAD

**Issue by kintz09** [material-foundation/material-theme-builder#147]
The theme builder utility in Figma and on the web is so incredibly powerful and useful. A few years ago I used a Material Design utility to generate the typography based on the fonts I selected. Does a utility like that exist for MD3? It would be amazing if this type of utility was built right into the Figma plugin, but even if a utility existed on the web that could be exported and then brought into Figma that would be valuable.

I did look around for this utility but didn't find anything. Hoping I just missed it. Thanks!

**Comment by margeeta** [comment]
We can't speak to our roadmap, but further theming features are on the horizon for theme builder.

**Comment by benjamincox** [comment]
@margeeta Could this plugin at least stop breaking the fonts I've changed in my theme until you actually implement typography? I change several fonts, but if I do ANYTHING in the Theme builder it sets them all back to Roboto.

**Comment by margeeta** [comment]
Type theming is planned for future update. 
Settings include an option to Update text styles, check this off.
