### ISSUE TITLE
Add image selector to web version

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [material-foundation/material-theme-builder#15]
It would be really nice to have the image selector in [web version](https://material-foundation.github.io/material-theme-builder/) like in Figma plugin:

![material-theme-builder](https://user-images.githubusercontent.com/7892779/143450838-931e5ec1-e8da-41d3-ba1f-adc2c4d7565e.png)

**Comment by FluorescentHallucinogen** [comment]
Oh, I absolutely didn't notice the "Add your wallpaper" button in the bottom right corner! 🙈

@rodydavis What about moving it to the rest UI elements on the left side to make it more visible?

![screenshot](https://user-images.githubusercontent.com/7892779/144625151-e6eb982c-e22f-44ec-b2bd-da601208a268.png)

**Comment by FluorescentHallucinogen** [comment]
@rodydavis I've found that if I select my own image via "Add you wallpaper" button, then when I switch from "Dynamic" to "Custom" tab, the extracted/calculated colors resets, so I can't see/copy/customize them.

**Comment by rodydavis** [comment]
This is working as intended. Dynamic tab is for just visualizing dynamic color, and the custom tab is for starting from baseline.

**Comment by FluorescentHallucinogen** [comment]
@rodydavis
> This is working as intended. Dynamic tab is for just visualizing dynamic color, and the custom tab is for starting from baseline.

But this is not how Figma plug-in works. In Figma plug-in when user switch from "Dynamic" to "Custom" tab, the extracted/calculated colors are not reset, so they can customize them. And this is a very useful feature! Users expect the same behavior as in Figma plug-in.

**Comment by FluorescentHallucinogen** [comment]
@rodydavis Moreover, "[support for keeping source colors between static/dynamic](https://www.figma.com/community/plugin/1034969338659738588/Material-Theme-Builder)" is one of the features/fixes of yesterday's Figma plug-in release. ;)
