### ISSUE TITLE
Custom primary colour is not maintained

### ISSUE THREAD

**Issue by bpappin** [material-foundation/material-theme-builder#150]
**Describe the bug**
I am reopening bug #8 as it should never have been closed without a solution.

**To Reproduce**
Please see bug #8 

**Additional context**

Bug #8, that custom primary colours are ignored, is a pretty vital one for making this product useful. 
Just about *every* developer/designer needs to know and trust what it's doing. 
However, it looks like the previous bug was closed without actually resolving the problem, and no information is forthcoming in that bug as to what is being done and where we can find it.

As a result, my peers feel that we should be the squeaky wheel.

**Comment by PhilDuc** [comment]
I would go further: I'd like an option to prevent adjustment of core colors (for example from my company's colors palette)
OK, the final color scheme may not be perfect (deal with it!), but we would get at least a quite consistent scheme.

**Comment by bpappin** [comment]
Looks like this is being ignored.
If you come across this ticket, make sure you comment or at least subscribe.

**Comment by MFlisar** [comment]
**This is not a solution but a workaround for _developers_ that just want a brand color based m3 theme and don't know enough about colors and designer stuff to create all the colors theirself or don't want to do that**

I found a homepage that offers a theme builder for Flutter - https://rydmike.com/flexcolorscheme/themesplayground-latest/ - its not from me but I use the themes in my [ComposeThemer](https://github.com/MFlisar/ComposeThemer) library...

On the side it has a copy color scheme option which allows you to export nearly working kotlin theme definition (just small adjustments are necessary, can be easily done with replace...).

**Feature**

It allows you to create brand color based themes (all I wanted) that are m3 compatible. Of course they are not perfect but as a developer I want something that works good and prefer this over perfect color definitions that ignore my brand color...

**How it works**

For example you can see in following screenshot that I easily created a full m3 gray theme - without any color blending (you just need to disable the defined scheme options as you can see it in the screenshot). I just defined the primary/secondary/tertiary colors and let the homepage do the rest..

And when you try to export that theme you will see that it has all the colors you need with the same names and all you need to do to make it working with kotlin is following:

* replace `:` with `=`
* replace `ColorScheme` with `colorScheme`
* replace the dark/light flag accordingly
* remove the shadow color

![grafik](https://github.com/material-foundation/material-theme-builder/assets/2437726/315041af-7ca7-4761-ad47-c0d303af3fe3)

Of course this won't give you perfect results but you get what you ask for...

**Comment by margeeta** [comment]
Color fidelity is now supported. Turn on color match in Settings, this will result in the input color to be assigned as container role.

**Comment by DavidMarquezF** [comment]
@margeeta The issue still persists. Both in the main colors and in custom colors (static colors) it will generate a result that uses similar colors but not the one I've specified, even when Color Match is enabled. Any idea why?
