### ISSUE TITLE
Surfaces 1-5 doesn't change when I change color theme

### ISSUE THREAD

**Issue by mrkilltop** [material-foundation/material-theme-builder#152]
Surface 1-5 colors doesn't change in all my projects. I tried Dynamic tab with source color, Dynamic tab with Image source, Custom tab but it case doesn't change.

Figma for macOS (tried on latest version on High Sierra and Ventura)

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/33777975/230058313-d78b8581-f372-4308-b32a-1bc01c679421.png">

**Comment by margeeta** [comment]
Hi @mrkilltop, 
You may need to check generate surface styles within Settings. 
![Screenshot 2023-04-05 at 12 12 37 PM](https://user-images.githubusercontent.com/10263978/230182202-9e1abc23-516c-45a3-bf49-fab4d8fc3b41.png)

Aside, we recently launch new surface roles: https://m3.material.io/styles/color/the-color-system/color-roles#0abbf8b7-61e1-49ee-9f97-4967beb1e4fe
Recent Figma update will generate them and the new color schematic is provide in M3 Design Kit.
