### ISSUE TITLE
New Surface Colors Don't Get Generated in the diagram

### ISSUE THREAD

**Issue by Tonihay** [material-foundation/material-theme-builder#157]
The generated diagram is only generating surface color
No surface Bright,Dim,Container ...

**Comment by margeeta** [comment]
New surface roles update as styles only, the M3 Design Kit has been updated with a new schematic. 
https://www.figma.com/community/file/1035203688168086460

**Comment by wildsylvan** [comment]
@margeeta
sorry if it's not the right place but... isn't this:

![image](https://github.com/material-foundation/material-theme-builder/assets/19886441/8b1f20be-5714-4007-92a9-5cc5b1f9878b)

gonna be updated to reflect the added tokens:

![image](https://github.com/material-foundation/material-theme-builder/assets/19886441/885f1afe-c6f3-4305-887b-c35b8ffb60a6)

?
