### ISSUE TITLE
Slow performance due to how style elements are inserted.

### ISSUE THREAD

**Issue by emilio** [material-foundation/material-theme-builder#158]
**Describe the bug**
https://m3.material.io/theme-builder#/dynamic is way slower than it needs to be. Investigating [a Firefox bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1828316) I noticed that the way you build your stylesheets is _very_ suboptimal.

See the analysis and test-case there, but TLDR instead of appending to a stylesheet in the DOM one property at a time, you should either disable the stylesheet, build it, then enable it, or build a single text node.

**To Reproduce**
1. Go to https://m3.material.io/theme-builder#/dynamic

**Expected behavior**
It's fast.

**Comment by romanr** [comment]
On a fastest computer and network it still takes few minutes every time you change any colour. Nobody can afford waiting times like that. It is the slowest Figma plugin I encountered.

**Comment by rgdagir** [comment]
Second that ^ changing anything on my themes and updating a library of components take ages....
