### ISSUE TITLE
Wrong flutter link Material/components/checkbox -> flutter

### ISSUE THREAD

**Issue by IagoAntunes** [material-foundation/material-theme-builder#159]
**Describe the bug**
https://m3.material.io/components/checkbox/overview
**To Reproduce**

**Expected behavior**
The correct link would be 
https://api.flutter.dev/flutter/material/Checkbox-class.html

**Screenshots**
![image](https://user-images.githubusercontent.com/63758301/232573707-7b231d36-5c44-4539-84fe-82d2d18614ea.png)

![image](https://user-images.githubusercontent.com/63758301/232573890-bb726435-a195-4bf1-870b-5087c8cfa951.png)

**Desktop **
 - OS: Windows
 - Browser Edge
 - Version 112.0.1722.48

**Additional context**
The correct link would be 
https://api.flutter.dev/flutter/material/Checkbox-class.html

**Comment by margeeta** [comment]
Thanks! I've filed this to the appropriate team to be updated. Closing.
