### ISSUE TITLE
Exporting text style changes not working

### ISSUE THREAD

**Issue by hjbrandt** [material-foundation/material-theme-builder#161]
**Platform:**
- Figma Desktop App version 116.7.103, Optimized for Apple Silicon
- Material Theme Builder
- Material 3 Design Kit (Community) 03.28.23 V1.8

**Description:**
When making changes to text styles in a Material Design Kit file I would expect that I'd be able to export those changes using Material Theme Builder, but those changes are not applied at export. Checking or unchecking "Generate Text Style" in the Theme Builder preferences has no effect in my testing. 

**Steps to reproduce:**
- Make copy of Community file
- Change text style property: M3 → display → large: from Roboto to Inter
- Run Material Theme Builder
- Export Theme File (JSON)
- Unzip and open file
- See that styles.display.large.fontFamilyName value = "Roboto"

**Expected and Actual Result**
Expected: styles.display.large.fontFamilyName = "Inter"
Actual: styles.display.large.fontFamilyName = "Roboto"

**Comment by benjamincox** [comment]
Exporting the actual typography would be great! But at present I'm more concerned about the fact that this breaks whatever font changes I made to the file as soon as I change a color.

**Comment by margeeta** [comment]
Exporting type theme is planned with type theming!
