### ISSUE TITLE
Provide roadmap for actual Material Styles support or rename the plugin

### ISSUE THREAD

**Issue by romanr** [material-foundation/material-theme-builder#164]
**Describe the bug**

- A material 3 website refers to "Figma Kit" and on Figma Plugin page it says with that it supports "**inspect elements** and **apply semantic color roles**." While Material 3 tokens include shape, fonts and others.
- There are issues reported when someone tries to do anything more than building colour themes, it fails.

**Expected behavior**

- If there's not going to be a full Theme support, Material Theme Builder should be renamed "Material Colour Builder"

or

Or if there is a plan to make it a full Theme Builder there should be a roadmap/checklist of progress:

- [x] Colour themes
- [ ] Shape
- [ ] Typography

Maybe someone would have built a plugin for M3 Shape and Typography plugins and  it's not happening because this plugin is blocking it with uncertainty.

**Comment by margeeta** [comment]
Hi, we are very limited on what we are able to announce. But you can expect typography theming in the future.
