### ISSUE TITLE
Styles not generating

### ISSUE THREAD

**Issue by antjtw** [material-foundation/material-theme-builder#169]
I can't generate styles for extended colours.

**Comment by margeeta** [comment]
Could you provide steps and possibly a screenshot of the issue? Also version (Figma or Web)?
Thanks!

**Comment by mtotschnig** [comment]
On the Web version, extended colors seem only to be generated if the "Harmonize" checkbox is not checked.

**Comment by margeeta** [comment]
@mtotschnig Thanks for adding more info. Seems to be populating after a couple seconds. Harmonize can be turned off and the extended colors remain. 
Will look into this some more!
