### ISSUE TITLE
Figma plug-in not generating any layer

### ISSUE THREAD

**Issue by Zeriss66** [material-foundation/material-theme-builder#170]
For some reason, the plugin stopped generating any kind of layer. It just generates styles.
<img width="1512" alt="image" src="https://github.com/material-foundation/material-theme-builder/assets/49654726/02615a21-c34e-495c-8945-417d26d72c33">

**Comment by margeeta** [comment]
Sorry for the inconvenience, the Material Theme Builder no longer generates the color diagram. 
The new color diagram can be sourced from the [M3 design kit](https://www.figma.com/community/file/1035203688168086460)

**Comment by Zeriss66** [comment]
Thank you for the response! Didn't know that
So how is this working now? Will I always need to go through the M3 Design Kit file in order to generate the color diagram?
I will basically have to duplicate the file source for every project?

**Comment by margeeta** [comment]
The diagram is wired up with Material tokens, so it can be swapped to any local theme. Duplicating the kit wouldn't be needed every time, just copy the diagram in where you've generated a theme and swap. 
We also released a playground file (accessed through **Try it Out**) which has the new color schematic.

**Comment by Zeriss66** [comment]
That's good to know! Thank you for the infos!
