### ISSUE TITLE
Kindly Add Support For Monochrome Theme ⚫️⚪️

### ISSUE THREAD

**Issue by Rajan-Patell** [material-foundation/material-theme-builder#173]
**Is your feature request related to a problem? Please describe.**
Currently this plugin not supported monochrome theme  

**Describe the solution you'd like**
Add monochrome theme generation support in plugin. please reference below link

**Additional context**
https://youtu.be/vnDhq8W98O4?t=843

**Comment by benjamincox** [comment]
Is this necessary? Or does Android monochrome-ize your colorful theme automaticaly?

**Comment by Rajan-Patell** [comment]
yes it's necessary because a  website theme must be started in black and white theme. so they were show it then its important

**Comment by margeeta** [comment]
Resolving as this is in-progress. Keep a look out for color fidelity/color match. It'll allow for lower chroma themes!

**Comment by Rajan-Patell** [comment]
okok

**Comment by KTibow** [comment]
@margeeta I don't think this was resolved - yes, you can use a monochrome color as your source color, but it still functions differently than the "monochrome" in [color utilities](https://github.com/material-foundation/material-color-utilities/tree/main/typescript/scheme)
