### ISSUE TITLE
Cannot export styles on Material Theme Builder (Custom) page

### ISSUE THREAD

**Issue by robert-lara** [material-foundation/material-theme-builder#174]
**Describe the bug**
When I fill everything out and attempt to export the styles, nothing happens. I do get this error in the console though:

```
app.js?version=1670027719620561:13291 Uncaught (in promise) TypeError: module$exports$google3$third_party$javascript$typings$jszip$index is not a constructor
    at module$exports$google3$ux$material$theme_builder$core$exporters$web$WebExporter.download (app.js?version=1670027719620561:13291:794)
```

**To Reproduce**
1. Go to 'https://m3.material.io/theme-builder#/custom'
2. Select the color picker for Primary and enter the following value for the color's hex value '#004225', then click 'Close'
3. Select the color picker for Secondary and enter the following value for the color's hex value '#FFEF00', then click 'Close'
4. Select the color picker for Tertiary and enter the following value for the color's hex value '#7BAA20', then click 'Close'
5. In the top right corner click 'Export' and select 'Web (CSS)'

nothing will happen, but when I open the chrome developer tools I do get the exception listed above

**Expected behavior**
For the theme to be exported

**Screenshots**
![image](https://github.com/material-foundation/material-theme-builder/assets/3268879/6952e05f-e1a8-45e9-b539-6c768d78caea)

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.3.1
 - Browser Chrome
 - Version 113.0.5672.92 (Official Build) (x86_64)

**Additional context**
None

**Comment by chrisjenx** [comment]
Yeesh 2 months no fix :(

**Comment by stevenbenitez** [comment]
Still broken. :(

**Comment by jonvillalobos** [comment]
cant download either

**Comment by adsonafonso** [comment]
still broken for me also :(

**Comment by jwill** [comment]
Unfortunately downloads being blocked is a known issue that happens unexpectedly for some in that version of Material Theme Builder.

The good news is that it's not an issue in the version that's under active development: https://material-foundation.github.io/material-theme-builder/
