### ISSUE TITLE
crashes on launch

### ISSUE THREAD

**Issue by vandym** [material-foundation/material-theme-builder#18]
figma plugin crashes/closes as it is opening up.... never seen a figma plugin do the magic trick

**Comment by rodydavis** [comment]
could you try with the latest release today?

Also would love to know more about the file in your project. can you try with an empty file and see if it is still an issue?

**Comment by vandym** [comment]
Nope ,, didn't work with an empty file either

Here's a recording
![CleanShot 2021-12-06 at 11 23 31](https://user-images.githubusercontent.com/8052783/144908996-86befbee-c759-4f4d-bb47-f3f3a9fcb4e2.gif)

**Comment by rodydavis** [comment]
That's really helpful! Thank you for sharing the video. Could you share more about your setup and install?

**Comment by vandym** [comment]
Figma desktop app
Running on Macbook Pro M1 Big Sur

btw similar behaviour in Chrome

Hope that helps

**Comment by rodydavis** [comment]
Can you try now? I think it was a font issue

**Comment by rodydavis** [comment]
Possibly related: https://github.com/material-foundation/material-theme-builder/issues/24

Please reopen if it is still an issue
