### ISSUE TITLE
Export to css missing and incorrect css variables

### ISSUE THREAD

**Issue by FenixTubluk** [material-foundation/material-theme-builder#181]
**Describe the bug**
When exporting some css variables are missing or have the incorrect variable.

Missing in the generated _tokens.css_
--md-sys-typescale-*-*-text-transform
--md-sys-typescale-*-*-text-decoration 

Incorrectly named in _typography.module.css_ or _tokens.css_
  - Current generated _typography.module.css_
    letter-spacing: var(--md-sys-typescale-*-*-tracking);
    line-height: var(--md-sys-typescale-*-*-height);

  - Should be this instead? as both *-letter-spacing and *-line-height exists in tokens.css
    letter-spacing: var(--md-sys-typescale-*-*-letter-spacing);
    line-height: var(--md-sys-typescale-*-*-line-height);

**To Reproduce**
Export a theme in the theme builder to css.

**Comment by jwill** [comment]
Thanks for the report.

At the present time, we're no longer generating typography in the versions under active development, neither Figma nor the web version at https://material-foundation.github.io/material-theme-builder/
