### ISSUE TITLE
Add support for Figma Variables for M3 Design Tokens

### ISSUE THREAD

**Issue by beingminimal** [material-foundation/material-theme-builder#182]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add support to select where user wants to generate design tokens either in figma styles or newly lunched feature figma variables.

**Describe alternatives you've considered**

**Additional context**

**Comment by romanr** [comment]
Or at least tell us if it's planned or not. After regular monthly updates, last update was 2 months ago and it wasn't significant one. Is this project going to be actively updated again?

**Comment by margeeta** [comment]
Variable support is planned.
