### ISSUE TITLE
Can't download theme in Chome

### ISSUE THREAD

**Issue by alexbirkett** [material-foundation/material-theme-builder#184]
**Describe the bug**
Can't download the theme

**To Reproduce**
* Open [the theme builder custom tab](https://m3.material.io/theme-builder#/custom)
* Click "Export"
* Select "Jetpack compose"

**Expected behavior**
* Theme is downloaded

**Actual behavior**
* Chrome blocks the download "because it's dangerous" 

**Screenshots**
<img width="1508" alt="Screenshot 2023-07-05 at 16 28 30" src="https://github.com/material-foundation/material-theme-builder/assets/530659/1976fc6a-99c7-407a-a3db-adc1f69227c5">

**Desktop (please complete the following information):**
 - OS: MacOS 13.3.1 (a) 
 - Browser Chrome
 - Version 114.0.5735.198 (Official Build) (arm64)

**Comment by adsonafonso** [comment]
I'm still seeing this issue. Seems to be only happening on MacOS @margeeta . I'm running MacOS 14.0
