### ISSUE TITLE
Remove or delete added themes

### ISSUE THREAD

**Issue by jpalmen** [material-foundation/material-theme-builder#188]
I'm always frustrated when I cannot delete or remove any of the themes I added to the Material Theme Builder plugin for Figma.

I would like a way to delete or remove themes I added to the Material Them Builder plugin for Figma.

**Comment by margeeta** [comment]
At the moment themes can be deleted from the Figma styles (right panel). Next time the plugin is opened they will not show. 
But, we do have an upcoming release that has rename and delete within the plugin.

**Comment by jpalmen** [comment]
Great! Thank you @margeeta. I appreciate the tip and look forward to the upcoming release!
