### ISSUE TITLE
[Feature request] Exporting themes for react-native-paper

### ISSUE THREAD

**Issue by bockoblur** [material-foundation/material-theme-builder#190]
**Describe the solution you'd like**
It would be great to be able to export created themes in format that could be directly imported to [react-native-paper](https://github.com/callstack/react-native-paper)

**Describe alternatives you've considered**
Maybe this should be a feature request for [react-native-paper](https://github.com/callstack/react-native-paper) repo? What do you think makes more sense? I also commented [there](https://github.com/callstack/react-native-paper/issues/1489#issuecomment-1627688127)

**Additional context**
* [Type definitions from react-native-paper](https://github.com/callstack/react-native-paper/blob/main/src/types.tsx)

**Comment by margeeta** [comment]
Thank you for your request. Sorry we have no plans on support react-native in exports. We do have json export, I wonder if that could be utilized in some capacity.
