### ISSUE TITLE
Chrome won't download the Flutter export.

### ISSUE THREAD

**Issue by MauScheff** [material-foundation/material-theme-builder#192]
**Describe the bug**
When I click export on Google Chrome Version 114.0.5735.198 (Official Build) (x86_64) there's a message in the download bar that says "material-theme.zip is dangerous, so Chrome blocked it (Discard)".

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Venture 13.4.1 (22F82)
 - Browser:  Google Chrome Version 114.0.5735.198 (Official Build) (x86_64)
 - Version:  Google Chrome Version 114.0.5735.198 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by solshuffle** [comment]
Having the same issue, it is not possible to download the Flutter theme.
<img width="404" alt="image" src="https://github.com/material-foundation/material-theme-builder/assets/13484862/e4fd535d-438e-4bb0-9573-4df528613d09">

**Comment by dzziwny** [comment]
exporting Flutter throws error in console

![image](https://github.com/material-foundation/material-theme-builder/assets/14834811/a382fe00-6fd6-4ab6-abd4-77f212c53b4f)

**Comment by maichongju** [comment]
Same problem. Please fix

**Comment by wfahnestock** [comment]
Hi all, it seems exports are working on Chrome 120.0.6099.130. See if you have any updates for Chrome before attempting to export.

Unfortunately, exports are broken on the latest Firefox, Version 121.0. They fail with error:
```js
Uncaught (in promise) TypeError: module$exports$google3$third_party$javascript$typings$jszip$index is not a constructor
    download https://m3.material.io/_mtb/app.js?version=1670027719620561:13291
app.js:13291:794
```

**Comment by jwill** [comment]
This was due to browser settings that would sometimes flag or interfere with the download library we were using.

Downloads are more consistent with our new version, please access it here instead: https://material-foundation.github.io/material-theme-builder/

**Comment by MauScheff** [comment]
Thanks! @jwill
