### ISSUE TITLE
Allow Defining the Error Color

### ISSUE THREAD

**Issue by johannesvollmer** [material-foundation/material-theme-builder#193]
Our Primary color is red. This conflicts with the auto-generated error color, which is also red. M3 allows a custom error color, which we would choose to be an orange hue. 

Can you provide an additional input field for defining the error in the theme builder?

As a workaround, we could probably add a custom color and replace the error color with that custom color in the generated theme, but that's not a great approach for experimenting color pallettes with the theme builder.

**Comment by margeeta** [comment]
Hello! 
Error is currently available in the Figma plugin. It is in progress for the web version.

**Comment by johannesvollmer** [comment]
Excellent, thanks a lot!
