### ISSUE TITLE
No surface container colors generated on web?

### ISSUE THREAD

**Issue by fr3nzy** [material-foundation/material-theme-builder#196]
_Surface_, _On Surface_, _Surface-Variant_ and _On Surface-Variant_ are the only surface colors generated, but material design guidelines include documentation on varying surface containers. Is this a feature yet to be implemented?

**Comment by bubbleguuum** [comment]
Why was this closed ?

**Comment by fr3nzy** [comment]
> Why was this closed ?

Because while the material theme builder website doesn't have these colors,  the [figma plugin](https://www.figma.com/community/plugin/1034969338659738588/Material-Theme-Builder) does

**Comment by bubbleguuum** [comment]
But shouldn't the "Android Views (XML)" web export  include these surface container colors (and a few other missing colors as well) ?

**Comment by treeder** [comment]
Will the website version have these soon? If there's no plans to update the website version, might want to remove it from the README and elsewhere so people don't try to use it.

**Comment by TheBrokenRail** [comment]
These colors seem to be used [quite extensively in the upcoming Material Components v1.11](https://github.com/material-components/material-components-android/commit/2114a11378fd801b32cd7431bb8a2c94de4f462c). As such including these colors in generated themes is quite important.

**Comment by margeeta** [comment]
Included with 2.0! 
https://www.figma.com/community/plugin/1034969338659738588/material-theme-builder
Web update is planned, but can access directly: https://material-foundation.github.io/material-theme-builder/
