### ISSUE TITLE
Feedback on Material Theme Builder Figma Plugin

### ISSUE THREAD

**Issue by umarzapta** [material-foundation/material-theme-builder#197]
Hi [Plugin Support Team],

I hope this message finds you well. I wanted to provide some feedback regarding the Material Theme Builder Figma plugin.
![Screenshot 2023-07-25 113244](https://github.com/material-foundation/material-theme-builder/assets/140484647/12284f42-6b39-4d5e-8b95-30e978089d11)

Firstly, I appreciate the plugin's capability to import the style guide into the right panel, making it convenient to access the design elements. However, I noticed that it does not create a color palette in the file as expected. This feature is essential for maintaining consistency and efficiency in the design process.

I kindly request your assistance in resolving this issue or guiding me on how to ensure the color palette is successfully imported.

Thank you for your attention to this matter, and I'm looking forward to an improved experience with the plugin.

Best regards,
[Umar]

**Comment by margeeta** [comment]
Thank you for your feedback. The Material Theme Builder no longer supports generating a color schematic. 
But the updated Material color schematic is available in the M3 design kit and Material Theme Builder playground file (accessed via **Try it Out** button on Figma plugin page).
