### ISSUE TITLE
Plugin creates M2 text styles also which should be optional

### ISSUE THREAD

**Issue by beingminimal** [material-foundation/material-theme-builder#2]
**Describe the bug**
When creating new styles in plugin, it is creating material v2 text styles also which should be optional.

**To Reproduce**
Check below video to check bug.
https://user-images.githubusercontent.com/84431724/139408388-9605db81-f0b6-45c1-9c3b-30d1844aea47.mov

**Expected behavior**
It should ask user to generate text style for M2, like it should be optional.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rodydavis** [comment]
Thank you for the feedback! This is something I am working to improve.

**Comment by margeeta** [comment]
Update includes option to generate Legacy M2 type styles.
