### ISSUE TITLE
Add link to GitHub repo on Material Theme Builder web version

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [material-foundation/material-theme-builder#20]
Currently, there is no any links from web version to GitHub repo.

What about e.g. adding GitHub icon to the top right corner?

![github-icon](https://user-images.githubusercontent.com/7892779/144713621-8f1128bf-a674-4c9f-9ff1-94facc97e7f1.png)

**Comment by rodydavis** [comment]
Thanks for the feedback!
