### ISSUE TITLE
Some colors become more pale after switching to the tone-based surfaces

### ISSUE THREAD

**Issue by PinkaminaDianePie** [material-foundation/material-theme-builder#201]
Not sure if that's a bug or expected behavior, but after switching to the new tone-based surfaces, some colors become more pale. I work mostly on the dark theme with filled cards, which uses `md.sys.color.surface-container-highest` token. Previously, such a card had a distinct influence of the primary color. Now, it looks just gray. I've tried to change my color palette to a different one multiple times, and every time neutral color and so container-highest were almost gray with little to no influence of the primary color. Old color palette were more vibrant, not it's just pale.

More of that, neutral and neutral variant colors are so similar to each other, that my eye can't even spot the difference between them. I always used `md.sys.color.on-surface` for the main text, like labels, and `md.sys.color.on-surface-variant` for the sublabels, but with a new color scheme, i just can't see any difference.

I don't know if it's the material design change and it's expected change, or it's a figma plugin thing, so not even sure where to ask these questions tbh. Switching to the tone-based surfaces made my designs uglier, and that's pretty sad. Sure, I can revert my `md.sys.color.on-surface-variant` to the one I had before these changes, so my text will be more readable, but I can't really do anything about the colors like `md.sys.color.surface-container-highest`, cause they didn't even existed before

**Comment by bubbleguuum** [comment]
Yes the the toned based surface seems to result in more muted colors, as if M3 was not pastel and muted enough...
