### ISSUE TITLE
material-automation repo is archive but pined

### ISSUE THREAD

**Issue by guyluz11** [material-foundation/material-theme-builder#203]
[material-automation](https://github.com/material-foundation/material-automation) repo is archived and at the same time pinned in the [material-foundation](https://github.com/material-foundation) organization GitHub page.

![image](https://github.com/material-foundation/material-theme-builder/assets/9304740/7bce4a14-3336-4134-90f2-b8566c1d9b80)

There is no reason to pin an archive repo, please remove it from there.

**Comment by margeeta** [comment]
Forwarded ticket to repo manager, closing this ticket.

**Comment by guyluz11** [comment]
@margeeta is there a link/ way to get notified about the state of it?
