### ISSUE TITLE
What do these buttons do?

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [material-foundation/material-theme-builder#21]
What do these 3 buttons (especially "Swap" button) actually do?

![buttons](https://user-images.githubusercontent.com/7892779/144741616-2c1e5551-1811-4e3a-ab63-7b83c54836e9.png)

After clicking on "Light" and "Dark" buttons, the colors for the light and dark theme become the same.

Is it a bug? See:

![dark](https://user-images.githubusercontent.com/7892779/144741619-91b61f24-8336-41e5-bea4-c7ee60f06ff6.png)
![light](https://user-images.githubusercontent.com/7892779/144741621-880c23c1-5a7d-4b83-b512-e96057216d76.png)

After clicking on "Swap" button, nothing happens.

What about adding hover tooltip on these buttons to explain what they actually do?

I've also found that there is no any activity indicator (progress bar) in Figma while the processes for these buttons are running.

**Comment by rodydavis** [comment]
Swap:
- Links the current selection of nodes to the current theme
- Migrates light and dark tokens to the current theme
- Useful for switching a large mixed (light/dark) selection between themes

Light/Dark:
- Links the current selection of nodes to the current theme
- Converts all tokens to the light or dark context
- This is useful for converting mixed tokens to all uniform
