### ISSUE TITLE
The Figma Plugin is not swapping the Text Style

### ISSUE THREAD

**Issue by altairps** [material-foundation/material-theme-builder#213]
This is very simple but is not working, when I hit SWAP button it only swap the color styles to the new one I just created with my custom prefix...  but there is no option to swap my Text Style (with new prefix too)

Is there another plugin that can help me with this?

**Comment by margeeta** [comment]
Currently, text styles need to be updated in the style properties. Text style updates can be swapped with the plugin. 
Once text style tokens are generated initially make sure to turn off the setting to prevent the plugin from resetting styles to baseline (Roboto):
![Screenshot 2023-09-11 at 3 06 04 PM](https://github.com/material-foundation/material-theme-builder/assets/10263978/704bead1-756c-4e34-8112-6113d70a7cc1)

![Screenshot 2023-09-11 at 3 03 48 PM](https://github.com/material-foundation/material-theme-builder/assets/10263978/0c447c14-2633-4d96-a5be-edc012595fc0)

**Comment by margeeta** [comment]
Closing due to age of ticket, release of new version, and planned typography theming work.
