### ISSUE TITLE
Why does it not include to generate tonal palettes?

### ISSUE THREAD

**Issue by havecodesoft** [material-foundation/material-theme-builder#219]
From what I can see your web based theme builder does have the feature to generate tonal palettes but not on your figma plugin. why?

**Comment by margeeta** [comment]
The tonal palettes are generated, they are found as reference tokens within styles. (Variables will be available soon)

Color schematic generation was removed to improve performance and color system updates, but it's still available in the playground file, design kit, and color design labs.

**Comment by havecodesoft** [comment]
Ok, thanks for the quick response. The playground file solved my issue.
