### ISSUE TITLE
Export values for extended colors

### ISSUE THREAD

**Issue by exploringbinary** [material-foundation/material-theme-builder#22]
I am using the Web version (Custom tab) to add Extended Colors. The exported theme (Color.kt for Compose) only includes one line per extended color, for example: val Custom0 = Color(0xFFb649b3)
 
I was hoping to have the Custom0, onCustom0, Custom0Container, and onCustom0Container colors defined in there as well (for all custom colors, and for both light and dark themes), matching what is displayed on the screen.  

I know that I can hover over the colors to get their codes but it would be more helpful to have them exported with the rest of the colors. They could be declared as vals like the other colors or even just listed in a block comment.

Thank you.

**Comment by tonyhallett** [comment]
Same for figma plugin

**Comment by ArchitecTJ37** [comment]
I am unable to export any extended color(s) as well.......not matter how I export (Theme.kt, XML, DSP using web/Figma Material Theme Builder), the extended colors are not included in the exported file.

Please push this fix as the high priority

**Comment by jwill** [comment]
Compose custom color is now exported in downloads.
