### ISSUE TITLE
[Web] token generation for font-weight has invalid values

### ISSUE THREAD

**Issue by mwahlhuetter** [material-foundation/material-theme-builder#222]
**Describe the bug**
The generated tokens for CSS have an incorrect value for font-weight. 
`--md-sys-typescale-label-small-font-weight: 500px;`

**To Reproduce**
1. Export for web from the theme builder
2. See wrong tokens

**Expected behavior**
The tokens are correctly generated.
`--md-sys-typescale-label-small-font-weight: 500;`

**Comment by jwill** [comment]
Thanks for the report.

At the present time, we're no longer generating typography in the versions under active development, neither Figma nor the web version at https://material-foundation.github.io/material-theme-builder/
