### ISSUE TITLE
Do not run the program every time I make a change - UX issue

### ISSUE THREAD

**Issue by nmanring0** [material-foundation/material-theme-builder#227]
**Is your feature request related to a problem? Please describe.**
No - other than the immense frustration I experience

**Describe the solution you'd like**
Include a SUBMIT or RUN or CREATE THEME button.

**Describe alternatives you've considered**
Not using the plug in.

**Additional context**
When you go to order a sandwich, you say "I'd like a turkey sandwich" - does the person making the sandwich go make the entire sandwich first or ask you for more details? Say they make it, then you say, "with american cheese and..." but they quickly go make the entire sandwich again with american cheese this time... "is that correct?" - "No I also wanted tomato and..." ... they rush to go remake the sandwich again, making you wait 5 minutes between each iteration...

There are 6 color fields to customize. To create a theme using this plugin, I have to wait for the entire process to run from start to finish, each time. Say it's 30 seconds to a minute. That's anywhere from 3-6 minutes just to create the theme initially, and go look at how it appears in my designs. Then I want to edit the colors again... it's PAINFUL. Please add a button to run the script when I'm done selecting my colors AND the options.

**Comment by nmanring0** [comment]
any updates regarding the neutral variant issue i reported in a different issue? that's a core problem where the theme doesn't update. also, has it dawned on anyone that the concept of Neutral Variant isn't discussed in Material's documentation on M3 color roles? The web based MTB doesn't include Neutral Variant, but the Figma tool does... WHY

**Comment by margeeta** [comment]
Neutral Variant and neutral are grouped together into Surface documentation. 
Web has a different deployment. 2.0 can be found here, with all the key colors: https://material-foundation.github.io/material-theme-builder/
