### ISSUE TITLE
Jetpack Compose color variables export does not include latest Material 3 colors

### ISSUE THREAD

**Issue by alesido** [material-foundation/material-theme-builder#230]
Jetpack Compose color variables export does not include latest Material 3 colors:
  
    surfaceBright 
    surfaceContainer 
    surfaceContainerHigh
    surfaceContainerHighest 
    surfaceContainerLow
    surfaceContainerLowest 
    surfaceDim

**Comment by StellarSand** [comment]
Same for xml too.

I guess they'll be added in the future as stated [here](https://github.com/material-foundation/material-theme-builder/issues/214#issuecomment-1720292381).

**Comment by margeeta** [comment]
They are now available!
