### ISSUE TITLE
Export to Flutter (Dart), continuous loading never ends

### ISSUE THREAD

**Issue by IrfanKnowledge** [material-foundation/material-theme-builder#235]
**Describe the bug**
Export->Flutter (Dart), but it's always loading never ends. Other option are no problem. 

**To Reproduce**
1. Go to '[Material 3 Design Kit](https://www.figma.com/community/file/1035203688168086460)' and open in Figma
2. Run 'Material Theme Builder (plugin)'
3. Export->Flutter (Dart)
4. Then it will error (always loading never ends)

**Expected behavior**
It should be download the file.

**Screenshots**
![Figma_Error](https://github.com/material-foundation/material-theme-builder/assets/45427562/2b7b55ed-f30c-40be-8d4a-d635e11a26e5)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 120.0.6099.129 (Official Build) (64-bit)

**Additional context**
Error detail can be seen inside browser console (see my screenshots).

VM17894:4268 Uncaught FormatException: Expecting '='
data:text/test.dart
    at Object.c (<anonymous>:4268:19)
    at Object.axF (<anonymous>:7276:53)
    at Object.f8 (<anonymous>:6867:19)
    at axL.Qk (<anonymous>:111554:16)
    at Po.abh (<anonymous>:111449:10)
    at Object.b72 (<anonymous>:10855:21)
    at Object.aU7 (<anonymous>:10853:23)
    at Object.be1 (<anonymous>:32510:77)
    at ace.a1i (<anonymous>:64308:10)
    at ace.aGt (<anonymous>:64252:6)

**Comment by iliyandpt** [comment]
Same here, tried all options. Only Dart is not downloading and loading forever.

**Comment by XK14** [comment]
Same

**Comment by marcocarmonapy** [comment]
Same

**Comment by wuchrchi** [comment]
I'm use mac meet the same question.

**Comment by margeeta** [comment]
Thanks y'all, we'll take a look after the holidays.
