### ISSUE TITLE
Add high contrast mode generator to Web version, same as in Figma

### ISSUE THREAD

**Issue by tartakovsky** [material-foundation/material-theme-builder#237]
In figma, there is an option to generate high contrast mode.
![image](https://github.com/material-foundation/material-theme-builder/assets/1624603/c1eeec94-cc6a-45b0-a401-5bc79899baf8)

As far as I can see, it isn't available in web version?

Would be great if it was made available :)

**Comment by jwill** [comment]
It is already in the web version that's under active development, check it out here: https://material-foundation.github.io/material-theme-builder/
