### ISSUE TITLE
Missing Dynamic and Custom buttons.

### ISSUE THREAD

**Issue by CheoR** [material-foundation/material-theme-builder#238]
**Describe the bug**
When using Material Them Builder plugin in Figma, I expect to see the `Dynamic` and `Custom` buttons at the top of the plugin.

**To Reproduce**
1. Run Material Theme Builder Plugin
2. See  `Dynamic` and `Custom` buttons missing.

**Expected behavior**
I expect to see the `Dynamic` and `Custom` buttons at the top of the plugin.

**Screenshots**
Plugin should showing `Dynamic` and `Custom` buttons.
![image](https://github.com/material-foundation/material-theme-builder/assets/5026476/bb6918b7-2ee4-4a66-9461-cffa863928cd)

Plugin actually not showing `Dynamic` and `Custom` buttons.
![image](https://github.com/material-foundation/material-theme-builder/assets/5026476/62de94eb-8973-4882-9eae-b1eed620281f)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox, Chrome
 - Version 120.0.1 
 -  Browser: Chrome
 - Version  120.0.6099.129

**Comment by ai-erickzhao** [comment]
With Respect,

How I can make perfect understanding between both in front of each if expect speech infrornt of all not only necessary,
Only vocabulary if can explain inside thoughts then without speak judge can do done as he/she after reading application or request expect listening lawyers.
Make sure you able to get someone's request or user way to ask from you?
It's too difficult or complicated for me to explain how I can tell to anyone what I need without making feed on top in trend, please attend with me & feel in which I only my own phasing, complicated philosophy.

**Comment by margeeta** [comment]
Hi! 
We recently released version 2.0 of MTB on Figma. You can read more about it on the [Material blog](https://material.io/blog/material-theme-builder-2-color-match).
Simplifying how color was used was a big part of the redesign, not only to make the UX simpler with all color sources in one place, but also performance wise.
