### ISSUE TITLE
Plugin fails to launch

### ISSUE THREAD

**Issue by PrattiDev** [material-foundation/material-theme-builder#24]
**Describe the bug**

The plugin will not launch because if fails to import Google Sans Regular.

**To Reproduce**
1. Try to launch the plugin.
2. View the console log.
3. Console will point out that Google Sans Regular is missing.

![6473d774-ad2f-4a6d-9587-079f4631720f](https://user-images.githubusercontent.com/17130024/145668970-ebffaea7-5959-47f7-8c26-029801e2e33c.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Also tested inside the stable app

**Comment by michalorestes** [comment]
Similar issue on Mac OS in Figma desktop app: 

```
Uncaught (in promise) RuntimeError: memory access out of bounds
    at jsvm-cpp.wasm:0x1eaeb
    at jsvm-cpp.wasm:0x3a8eb
    at jsvm-cpp.wasm:0x251ec
    at jsvm-cpp.wasm:0x32d01
    at jsvm-cpp.wasm:0x2b339
    at jsvm-cpp.wasm:0x2ac73
    at jsvm-cpp.wasm:0x13ff
    at jsvm-cpp.wasm:0x131c
    at jsvm-cpp.wasm:0x24f6
    at jsvm_runMicrotasksAndAutorelease (jsvm-cpp.wasm:0x71f9)
    at Object.Module._jsvm_runMicrotasksAndAutorelease (jsvm-cpp.js.br:8)
    at figma_app.8984b6a00d…c6a84.min.js.br:844
```

**Comment by rodydavis** [comment]
I will fix this tomorrow 👍🏼

**Comment by rodydavis** [comment]
Just pushed a hot fix!
