### ISSUE TITLE
custom colours are not saved

### ISSUE THREAD

**Issue by bravilordesign** [material-foundation/material-theme-builder#242]
When I try to create a theme by changing the different base colours, it doesn't update it at all after clicking update. It will simply create a colour library with the previous colour values. So no matter what I change, the result remains the same...

**Comment by margeeta** [comment]
Could you provide steps and screenshots to help reproduce? 
Thanks

**Comment by bravilordesign** [comment]
My apologies for the late reply. 

1. Select an icon in your design.
2. Apply a different colour (either from library or custom)
3. Open Material Symbols
4. Replace the current icon with a new one.
5. Icon changes, but also changes colour

https://github.com/user-attachments/assets/0c9de411-2776-45dd-9ec6-36ada4e0c521

**Comment by bravilordesign** [comment]
@margeeta
