### ISSUE TITLE
Color fidelity feature seems not to be available in web version

### ISSUE THREAD

**Issue by PhilDuc** [material-foundation/material-theme-builder#245]
Scheme colors fidelity is a major feature but it is not to available in the **web version** of MTB.
The "match color" option seems to be missing whereas it is essential when dealing with a corporate palette.

**Comment by ismailhouman** [comment]
There are two web tools called 'Material Theme Builder'. If you want the same features as the Figma plugin, including the 'color match' option, just use the one at [Material Theme Builder](https://material-foundation.github.io/material-theme-builder/).

For more info, check out the official source: [Material Color Utilities](https://github.com/material-foundation/material-color-utilities?tab=readme-ov-file#design-tooling).

**Comment by margeeta** [comment]
This is correct, for newer features, please use the Github version as we work on updating the Material.io version. Thank you!
