### ISSUE TITLE
Export Button on Custom M3 Builder Web page Not working on MacOS

### ISSUE THREAD

**Issue by adsonafonso** [material-foundation/material-theme-builder#247]
**Describe the bug**
Create a custom color palette and trying to export it to android.xml or Jetpack Compose (Theme.kt), or any option for that matter
click on the export button and nothing happens.
https://m3.material.io/theme-builder#/custom

**To Reproduce**

1. Go to create palette
2. Click on export and pick Android XML, Jetpack Compose
3. see nothing happens and no dowload triggered or saved to download directory
4. not working in both Chrome and Safari

**Expected behavior**
Should get a zip file download

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.0
 - Browser [chrome] also happening on Safari tho
 - Version [120.0.60999]

**Comment by jwill** [comment]
Unfortunately downloads being blocked is a known issue that happens unexpectedly for some in that version of Material Theme Builder.

The good news is that it's not an issue in the version that's under active development: https://material-foundation.github.io/material-theme-builder/
