### ISSUE TITLE
Doesn't create Dark / High Contrast etc modes in tokens, only Light

### ISSUE THREAD

**Issue by glennbull** [material-foundation/material-theme-builder#249]
Self explanatory I think.

**Comment by ryansnowden** [comment]
I haven't checked - but.. If you are using a free account it will only do light because Figma wants you to pay.

**Comment by margeeta** [comment]
All contrast themes are generated as variables, but Figma limits modes to paid plans and tiers. MTB will continue generating styles, so everyone can utilize all contrast themes.

**Comment by glennbull** [comment]
We're on a paid Figma plan and I can add the modes on manually.  Is it a case where Figma is preventing the plugin from adding multiple modes?
