### ISSUE TITLE
Two Theme builder live websites

### ISSUE THREAD

**Issue by Basyras** [material-foundation/material-theme-builder#256]
**Describe the bug**

From this blog post: https://material.io/blog/material-theme-builder I got this link to theme builder website: https://m3.material.io/theme-builder

Seems like the website is not the most updated one e.g. not using new elevation system described here:  
https://material.io/blog/tone-based-surface-color-m3

Later I found this issue: https://github.com/material-foundation/material-theme-builder/issues/214
where @margeeta provided link to another website: https://material-foundation.github.io/material-theme-builder
that appears to be more "updated" but as already stated here https://github.com/material-foundation/material-theme-builder/discussions/244 it is missing `tokens.css` and `typography-module.css` when exporting to web.

My questions:

1. Is the first link (https://m3.material.io/theme-builder) sort of production version that is not (yet) updated and the second link (https://material-foundation.github.io/material-theme-builder) is some staging one or we are having two websites running in parallel.
2. Is there a reason (or bug) in second website that is missing `tokens.css` and `typography-module.css`?

**To Reproduce**

1. Visit https://m3.material.io/theme-builder website
2. Export to web
3. observe missing new surfaces colors
4. Visit https://material-foundation.github.io/material-theme-builder website
5. Export to web
6. observe surface colors added but missing `tokens.css` and `typography-module.css`

**Expected behavior**
Only one website existing with both surfaces colors and `tokens.css` and `typography-module.css`

**Comment by kelvin2200** [comment]
Man, I thought I was loosing my mind. 
I somehow ended on the material-foundation's theme builder and I downloaded a theme as a JSON, had to close my browser, and when I searched for it again, I landed on the theme builder on m3.material.io.
I noticed weird things happening, like demo buttons not being clickable, and that the export didn't have a JSON export.
Took me a while to retrace my steps and realize they're 2 different websites.
Confusing.

Also, what's with the `high-contrast` and `medium-contrast` schemes?
I can't find any way to generate those using the material color utilities...

**Comment by margeeta** [comment]
The Github page version has been a staging version of MTB web, we decided to open it up to give user's earlier access to updates. 
You can read more about 2.0 updates (including Color Contrast) in the latest blog: https://material.io/blog/material-theme-builder-2-color-match
