### ISSUE TITLE
Export does not export theme with correct names; save colors saved or rename files correctly

### ISSUE THREAD

**Issue by meslange** [material-foundation/material-theme-builder#263]
When I export Android XML, I do not see the the theme name correctly exported. 

Please provide documentation or explain how to export customized xml/json files. Thank you!

**Comment by meslange** [comment]
1. created new theme: 
tester
<img width="884" alt="Screenshot 2024-02-08 at 9 53 51 AM" src="https://github.com/material-foundation/material-theme-builder/assets/159472660/6ff3bc15-1b8f-495c-9e34-6bd45d9f5d2a">

2. customized new core colors
<img width="655" alt="Screenshot 2024-02-08 at 9 56 26 AM" src="https://github.com/material-foundation/material-theme-builder/assets/159472660/a30bbac2-9c78-4bd6-bf59-f308b9afb006">

3. export Android view
<img width="609" alt="Screenshot 2024-02-08 at 9 59 09 AM" src="https://github.com/material-foundation/material-theme-builder/assets/159472660/5938a920-2d74-4032-8278-579f28d18494">
<img width="645" alt="Screenshot 2024-02-08 at 10 00 27 AM" src="https://github.com/material-foundation/material-theme-builder/assets/159472660/6b06400b-9dbf-4e28-bb31-7b2cf08b573a">

4. 'material-theme' shows up instead of 'tester'
<img width="425" alt="Screenshot 2024-02-08 at 9 59 39 AM" src="https://github.com/material-foundation/material-theme-builder/assets/159472660/e0cde5e7-3143-4ba0-a71d-148b3b07677f">

5. when i open the files these are what i see: 
<img width="692" alt="Screenshot 2024-02-08 at 10 01 08 AM" src="https://github.com/material-foundation/material-theme-builder/assets/159472660/287ece07-87ee-4e8c-ad54-6e07a3a1ab05">
<img width="587" alt="Screenshot 2024-02-08 at 10 01 24 AM" src="https://github.com/material-foundation/material-theme-builder/assets/159472660/cd3f9d30-5518-400b-a557-11a4f619d681">

6. Since I have a custom theme 'tester' and it's actively up, i would expect to be able to export out the custom theme in xml, json files, etc. 

Please help explain how I might export the custom themes created as android /json files

**Comment by margeeta** [comment]
Can you close the Material Theme Builder plugin and try running again? There is a new version out.

The previous versions didn't rename the export to the theme name, it would export as 'material-theme, but the colors are updated. #F90087 is your pink source color.
![Screenshot 2024-02-08 at 10 14 02 AM](https://github.com/material-foundation/material-theme-builder/assets/10263978/05b663e0-630c-4323-8dee-d62e8ffc608a)

**Comment by meslange** [comment]
so the new version will rename?

**Comment by margeeta** [comment]
Yes

**Comment by meslange** [comment]
i can't seem to remove the plugin and it shows it as locked;—how can I update the plugin?

**Comment by meslange** [comment]
In digging through the plugin docs for Figma it looks like: 
- updated versions are automatically published for users
- there isn't a clear way to remove the plugin to 'reinstall'

**Comment by margeeta** [comment]
Oh! Can you message me internally at ivyknight?
