### ISSUE TITLE
On the Material Theme builder page, there is a missing image

### ISSUE THREAD

**Issue by talamaska** [material-foundation/material-theme-builder#265]
**Describe the bug**
Missing image in the Material theme builder

**To Reproduce**
1. Go to [https://m3.material.io/theme-builder#/custom](https://m3.material.io/theme-builder#/custom)
2. the emulated mobile screen

**Expected behavior**
Expecting the image to load

**Screenshots**
![image](https://github.com/material-foundation/material-theme-builder/assets/299973/5fc53401-2b80-4c1d-b01a-c1703d446b88)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 122.0.6261.58

**Comment by bigshrey** [comment]
When accessed, URL shows 404 error.
Also, the request might be blocked:
![image](https://github.com/material-foundation/material-theme-builder/assets/156182283/deeb0232-e268-4bba-8f9f-944616e7ab2e)
