### ISSUE TITLE
Question: Set "exact" colors in theme palette?

### ISSUE THREAD

**Issue by tbsbdr** [material-foundation/material-theme-builder#27]
Thanks a lot for all the work!!
Did I get get it right: If the primary color of my companies styleguide is eg. `#ff0000` and I'll use it as key primary color, it will always be transformed to primary theme palette color `#c10000`? So it's mostly not possible to set "exact" colors in the theme palette, right?

![image](https://user-images.githubusercontent.com/26610733/146986800-e9fa7727-7aa8-47bc-b709-43783d048680.png)

**Comment by margeeta** [comment]
Correct the tool won't give you the exact color you have input, but one that is shifted to fall into the Material 3 color space for improved accessibility. 
Custom colors can be added under Extended colors that will export non-shifted colors out.
Although, not suggested, we understand if you need exact colors in the theme: The colors can still be edited in the export files directly or the figma styles (if using the figma plugin, which will also check for contrast).
