### ISSUE TITLE
Ability to rename custom color and change default primary value (instad of custom040)

### ISSUE THREAD

**Issue by rahulgajjar** [material-foundation/material-theme-builder#28]
When the custom color is added it is being added as custom0 and custom1 which is not helpful.

By default, the Material theme does not generate the colors for Warning or Success. When those colors are added to the theme as custom colors, it would help to identify which color is used for which. This is extremely helpful when the created styles are used by many designers on the team who maybe are not familiar with technical terms.

My purpose of adding custom color is to keep some color static, like brand color or the warning, success colors. While keeping the ability to change colors dynamically for another part of the UI. Renaming the field would help to make a clear distinction.

The second issue is there is no way for me to define proper success and warning color following the current scheme where it automatically selects the value 40 for the custom color. Even in the example image shown on the material3 website, I would not be able to get those orange and green colors.

![image](https://user-images.githubusercontent.com/8909523/148101724-eed8d7bc-c597-43b7-827c-631829cf2983.png)

![image](https://user-images.githubusercontent.com/8909523/148102278-333de49e-32f7-48fa-8ac8-3e410c4c0d8b.png)

**Comment by PrattiDev** [comment]
I want this so, so badly. The fact we can't insert a shade to a custom token makes creating original designs with dynamic color impossible within Figma.

When the plugin was first released, I thought this would be an option. In any case, one of the ideas I've had was to write the desired shade as a description of a color style and have it be recognized by the plugin and assigned properly.

![Token](https://user-images.githubusercontent.com/17130024/149644739-de82db60-80b9-4bdf-ad44-103f8259be23.png)

Haven't really gone through all the edge cases and potential accessibility issues. I'm sure Google's designers would know it best. It's a very important feature that I think deserves more attention.

**Comment by rodydavis** [comment]
Just added support for custom color, rename and delete on the web version! 🎉

https://material-foundation.github.io/material-theme-builder/#/dynamic

Working on rename support for the Figma version.

**Comment by rodydavis** [comment]
This is as designed, but the original key color used as input will be available in export. If it is not or missing on a platform please file an issue!

and you are welcome 🎉
