### ISSUE TITLE
Fixed Accents are not exported by the theme builder

### ISSUE THREAD

**Issue by etyarews** [material-foundation/material-theme-builder#281]
**Describe the bug**
Fixed Accents are missing from the export options of both the Figma Tool and the Web Builder

**To Reproduce**
1. Go to a theme builder
2. Click on 'export'
3. Scroll down to any option
4. See the files exported and see there's no fixed variation

**Expected behavior**
The theme builder was updated recently and I was expecting it to generate all the tokens mentioned at m3.material.io

**Additional context**
The Figma Tool itself generates the Fixed accent colors, and you are able to design components inside Figma using them, but they are missing when exporting, which complicates the hand-off between designer and programmer, as there's no alternative right now to the fixed accents

**Comment by sealotus94** [comment]
This is happening for me too.

**Comment by jwill** [comment]
Fixed tones are not universally available on every platform. And even when available, they did not hit each platform at the same time. So they are exported in accordance to what a recent version of that platform has available.

If these tones are absolutely necessary and the platform/export doesn't have it, use extended color.

**Comment by etyarews** [comment]
It is part of the guidelines, how is it not planned? 

And how the hell are we supposed to use extended colors for the same functionality as those fixed tones?
