### ISSUE TITLE
Material Theme Builder PopUp not responsive

### ISSUE THREAD

**Issue by Estefania-Demitropulos** [material-foundation/material-theme-builder#30]
![image](https://user-images.githubusercontent.com/53885077/149208196-a285c8b4-db4d-41f5-a429-1376f93b0f08.png)
Hi! I loved the plugin but there is a row of buttons I can't see. I tried it on a bigger screen but still can't see the row of buttons. The popUp  stays the same.
I inspected the browser app and found out one of the elements has a fix height, while the other elements have their heights set on 100%
I dont know if this is the root of the problem, but I hope this helps.
Thanks!

**Comment by rodydavis** [comment]
Thank you! I was having a weird issue with height: 100%. But i will try a few things to fix it.

Is your system font or display scaled at all?
