### ISSUE TITLE
Inside Figma missing the visual layers

### ISSUE THREAD

**Issue by RonenTavor** [material-foundation/material-theme-builder#302]
**Describe the bug**
There is no representation of the actual layer, colors, or text.
Where does this fantastic capability disappear?
I can see in live that the colors change.

**To Reproduce**
1. open the plugin
2. Click on Create team
3. no visual representation

**Expected behavior**
View the color scheme as in the Figma file inside "material design 3 kit."

**Screenshots**
<img width="1209" alt="Screenshot 2024-05-02 at 13 43 47" src="https://github.com/material-foundation/material-theme-builder/assets/116493230/14d89f5b-084e-4359-8efb-a1d0bcf615e4">
This picture is from your kit, and this part needs to be included for me.

**Desktop (please complete the following information):**
 - OS: MacOS
- Figma desktop version.

**Comment by margeeta** [comment]
We had to remove it for performance issues, but it is in the playground file and design kit file. 
Both can be swapped to to your theme.

**Comment by RonenTavor** [comment]
Hi Ivy,

Where is the playground file?
Inside the Figma file "material design kit (community)" there is no option
to edit and swap colors.
Can you please elaborate more on how I can edit and swap the color?

Thanks,
Ronen

**Comment by margeeta** [comment]
From the community page: https://www.figma.com/community/plugin/1034969338659738588/material-theme-builder
Click **Open with…** and then **+Playground File**
