### ISSUE TITLE
Selecting a source image in Material Theme Builder (website) doesn't provide a selection of source colors

### ISSUE THREAD

**Issue by quoc-huynh-cosee** [material-foundation/material-theme-builder#303]
**Describe the bug**
Using the Material Theme Builder with a **source image** in [Figma](https://www.figma.com/community/plugin/1034969338659738588/material-theme-builder) you'll get a selection of **source colors**. If I'm using the Material Theme Builder with a **source image** on the [website](https://material-foundation.github.io/material-theme-builder/) , you won't get a selection of s**ource colors**. Is there any reason why?

**To Reproduce**
Steps to reproduce the behavior (Figma):
1. Go to Figma
2. Open the Material Theme Builder plugin
3. Select a source image
4. You can now select a source color

Steps to reproduce the behavior (Website):
1. Go to https://material-foundation.github.io/material-theme-builder/
2. Select a source image
4. You don't get a selection of source colors.

**Expected behavior**
The website also gets a selection of source colors.

**Screenshots**
Figma:
<img width="349" alt="Figma" src="https://github.com/material-foundation/material-theme-builder/assets/93118554/d1cab605-c8a5-40f7-b469-2718a95ea500">

Website:
<img width="549" alt="Bildschirmfoto 2024-05-14 um 10 32 44" src="https://github.com/material-foundation/material-theme-builder/assets/93118554/697147bf-e97c-46fc-b212-93f82457a64a">

**Desktop:**
 - OS: MacOs Sonoma 14.4.1
 - Browser: Firefox Browser 125.0.3 (64-Bit)

**Comment by margeeta** [comment]
Thanks for the question! The Figma version allows for more exploration overall, where the web version is more direct in creating a theme.
