### ISSUE TITLE
how to use 'extended color' in flutter ?

### ISSUE THREAD

**Issue by lien-dkseo** [material-foundation/material-theme-builder#304]
```dart
// theme.dart
class MaterialTheme {
  ...

  /// Custom Color 1
  static const customColor1 = ExtendedColor(
    seed: Color(4290465906),
    value: Color(4290465906),
    light: ColorFamily(
      color: Color(4287449693),
      onColor: Color(4294967295),
      colorContainer: Color(4294957537),
      onColorContainer: Color(4281992986),
    ),
    ...
  );

  /// Custom Color 2
  static const customColor2 = ExtendedColor(
    seed: Color(4286067527),
    value: Color(4286067527),
    light: ColorFamily(
      color: Color(4287449691),
      onColor: Color(4294967295),
      colorContainer: Color(4294957536),
      onColorContainer: Color(4281992985),
    ),
    ...
  );


  List<ExtendedColor> get extendedColors => [
    customColor1,
    customColor2,
    customColor3,
    ...
  ];
}
```

how to use 'static const customColor1, 2, ...' or 'get extendedColors' in flutter ?

**Comment by bhargavweb** [comment]
Here is how I would use it:

ThemeData darkMediumContrast() { // Update the other similar methods also
    return theme(darkMediumContrastScheme().toColorScheme(),
        divider: MaterialTheme.divider.darkMediumContrast);
  }

ThemeData theme(ColorScheme colorScheme, {required ColorFamily divider}) =>
      ThemeData(
          useMaterial3: true,
          brightness: colorScheme.brightness,
          colorScheme: colorScheme,
          textTheme: textTheme.apply(
            bodyColor: divider.color, // Example
            displayColor: divider.onColor, 
           )
       )
   );

**Comment by lien-dkseo** [comment]
@bhargavweb thank you~.

I edited the question.
`customColor1, customColor2, ...`

I want to use it like this....
`Theme.of(context).....customColor1.onColor`
`Theme.of(context).....customColor1.colorContainer`

```dart
Icon(
  Icons.warning_amber,
  color: Theme.of(context).colorScheme.primary, // like this... Theme.of(context).....customColor1.onColor
),
```

**Comment by jwill** [comment]
What you are describing sounds like Theme Extensions: https://api.flutter.dev/flutter/material/ThemeExtension-class.html

Which solution you choose can be determined by your needs (e.g. will the color be the same across light, dark, and contrast levels or need to be contrast aware)
