### ISSUE TITLE
The theme exporter for Flutter contains deprecated code

### ISSUE THREAD

**Issue by chardinson** [material-foundation/material-theme-builder#305]
`scaffoldBackgroundColor: colorScheme.background,`

> 'background' is deprecated and shouldn't be used. Use surface instead. This feature was deprecated after v3.18.0-0.1.pre. (Documentation)  Try replacing the use of the deprecated member with the replacement.

---

`background: background,`

> 'background' is deprecated and shouldn't be used. Use surface instead. This feature was deprecated after v3.18.0-0.1.pre. (Documentation)  Try replacing the use of the deprecated member with the replacement.

---

`onBackground: onBackground,`

> 'onBackground' is deprecated and shouldn't be used. Use onSurface instead. This feature was deprecated after v3.18.0-0.1.pre. (Documentation)  Try replacing the use of the deprecated member with the replacement.

---

`surfaceVariant: surfaceVariant,`

> 'surfaceVariant' is deprecated and shouldn't be used. Use surfaceContainerHighest instead. This feature was deprecated after v3.18.0-0.1.pre. (Documentation)  Try replacing the use of the deprecated member with the replacement.

**Comment by KavanBahrami** [comment]
Came here to post this issue.
