### ISSUE TITLE
The Fonts functionality only allows fonts from predefined list

### ISSUE THREAD

**Issue by romanr** [material-foundation/material-theme-builder#310]
**Describe the bug**

Can use Font only if it's in plugin's list.

**To Reproduce**
1. Go to '**A** tab'
2. Click on font select.
3. Input Font name that's not in the list.
4. Unable to save value using Enter key or otherwise.

**Expected behavior**
Allow enter any font name.

**Comment by jwill** [comment]
This is working as intended. Only fonts available via Google Fonts are available at this time
