### ISSUE TITLE
Figma plugin exported dsp md.sys.color.inverse-on-surface.dark is incorrect

### ISSUE THREAD

**Issue by tonyhallett** [material-foundation/material-theme-builder#32]
**Describe the bug**
Figma plug dsp is incorrect for 
md.sys.color.inverse-on-surface.dark

It is returning md.ref.palette.neutral10 when it should be md.ref.palette.neutral20

**To Reproduce**
Use the Material Theme Builder plugin to build a theme.
Export dsp

**Expected behavior**
md.ref.palette.neutral20

**Screenshots**

Desktop - Windows 10

**Comment by tonyhallett** [comment]
Same results from Web

**Comment by rodydavis** [comment]
I will double check on this value, thank you!
