### ISSUE TITLE
Match Colors is misleading

### ISSUE THREAD

**Issue by bpappin** [material-foundation/material-theme-builder#327]
**Describe the bug**
When choosing the Match Colors options, I would expect the primary role to match the primary colour specified. 

This is not happening, its close, but to designer, QA, and management who don't understand what's happening, it is simply the wrong colour. 

**To Reproduce**
This is demonstrable on the Web version of the Material Theme Builder.

**Expected behavior**
When I specify a specific colour, and request the builder not to change it by checking the "Match Colors" option, then I expect it not to change the colours.

**Additional context**
Although I love the way the colours organize themselves for Material3, when building a product, I am usually required to use **a specific colour** for some things, and _I just need the core colours to remain *exactly* as the are specified_.

**Comment by JihaneSDN** [comment]
Same problem here on the web as well as in the desktop version. And I am expecting the same behaviour as you described.

**Comment by margeeta** [comment]
Hey y'all, sorry for the confusion. Color match adds the input colors as the container colors in order to keep contrast between all the other roles. I've shared feedback back to the team, we're always looking for ways to improve the systems.

**Comment by bpappin** [comment]
> Hey y'all, sorry for the confusion. Color match adds the input colors as the container colors in order to keep contrast between all the other roles. I've shared feedback back to the team, we're always looking for ways to improve the systems.

As a designer and a developer, I really appreciate the assistance in keeping everything balanced.
However, clients are extremely picky about their colours, and we really need a switch that will simply turn off all the smart tools, and keep what we set. 
Alternatively, It would be ideal if the bulk was generated, as it is now, from the primary colour, but in "fixed" mode, a user altered colour should become "sticky" and not change, unless explicitly reset.
