### ISSUE TITLE
Material Theme Builder does not work with Figma Free plans

### ISSUE THREAD

**Issue by leonrubins** [material-foundation/material-theme-builder#328]
Dark modes fail to update on Figma free plans

**Comment by dj-256** [comment]
I did not know it was linked to the free plan but I think I am experiencing the same thing. I cloned the MD3 kit figma file and tried to run the plugin in it. It did not change the dark palette at all
![Screen Shot 2024-08-05 at 4 31 46 PM](https://github.com/user-attachments/assets/09e508be-395b-4da9-8b76-9745cd202856)

**Comment by margeeta** [comment]
We've kept generation of styles on in order to keep working with the free plan.
