### ISSUE TITLE
Changing fonts breaks Android Schemes generation

### ISSUE THREAD

**Issue by PrattiDev** [material-foundation/material-theme-builder#33]
**Describe the bug**
Once two or three text styles have their fonts changed, the plugin will no longer be able to generate Android Schemes, and will crash when attempting to do so.

**To Reproduce**
1. Change the font of two or three text styles. In this case, I used Display/Large, Medium, Small, and changed their font to **Manrope**.
2. Attempt to generate Android Schemes from the context menu of Figma.
3. The plugin will launch but crash almost instantly.

The error shown is as follows:

![chrome_9EN7clXyM3](https://user-images.githubusercontent.com/17130024/151246520-7ffc8b36-0ee2-4a09-b3f2-ae97b18d7d55.png)

**Expected behavior**
Android Schemes should ideally, update automatically, as per #13 . However, in this instance, the plugin should at least generate Android Schemes and update those color styles regardless of the font chosen.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 97.0.4692.99 (Official Build) (64-bit)

**Comment by rodydavis** [comment]
Yep this is a Figma issue I have been working on.

I am making sure to load the font but it still fails randomly.

Im working on improving the typography support
