### ISSUE TITLE
The Dynamic and Custom options are not visible in the top bar

### ISSUE THREAD

**Issue by Petr80** [material-foundation/material-theme-builder#336]
In Web version (but also in Figma) I don't see the possibility of selecting **Dynamic** or **Custom** colors in the top bar, see image:
![image](https://github.com/user-attachments/assets/787473d8-760d-4040-bb4f-12b06b458055)
There is only Dynamic colors.

But in your quide is visible:
![image](https://github.com/user-attachments/assets/516f89b0-91e5-4fc4-ad6a-8cab73ba087a)

**Comment by margeeta** [comment]
The readme has been updated for web. You can read more on the 2.0 update and merging dynamic and custom color options here: https://m3.material.io/blog/material-theme-builder-2-color-match

Thanks!
