### ISSUE TITLE
"Swap color variables" documentation

### ISSUE THREAD

**Issue by duncanhoge** [material-foundation/material-theme-builder#337]
It is unclear from the Readme how to actually swap variables applied to the UI kit from the default purple theme when a new theme has been generated. I would expect the ability to update the UI Kit with the theme that was generated, but it doesn't seem possible when using the UI kit.

**Comment by margeeta** [comment]
Thanks for the question! Swapping themes with libraries (UI Kits) has to be done manually as we aren't able to access the library variables or styles. Be careful when theming the UI Kits, as they can override local changes when updated.
