### ISSUE TITLE
Doesn't work well

### ISSUE THREAD

**Issue by realchugunov** [material-foundation/material-theme-builder#340]
Hello staff team, hoping you an amazing day. 

The problem with the material design 3 kit is;
Old version was way too much better than this new version. I'm importing dark components to my workflow but all component is light mode, its like a bug and I can't change it no matter what. Please bring the old version so we can choose the exact thing we want = Dark & Light together at the same page with the whole components.

**Comment by realchugunov** [comment]
"Showkit" is not working too, it opens a blank space as a "untitled" project.

**Comment by margeeta** [comment]
Thanks for your feedback, I'll share with the team. The kit was recently reorganized and simplified, including using variables for dark and light themed components. This means components can be swapped easily using Figma modes.

Showkit, opens a blank file and shows the UI library within the asset panel. 
Make a copy will duplicate the kit file. So depends on if you want to use as a connected library or have a local copy.
![Screenshot 2024-08-15 at 10 46 48 AM](https://github.com/user-attachments/assets/317ef1f2-2809-4f0d-92e0-2aace8ce68f3)
