### ISSUE TITLE
Figma theme builder plug in

### ISSUE THREAD

**Issue by nschultz-dragon** [material-foundation/material-theme-builder#341]
The theme builder plug in is not working in Figma. It does not correctly generate the colors and it does not create the artboard with the color.
I have tried to get it to export in Json but am having issues with getting that in figma and it will not give me the artboard with color examples.
Could you help?

**Comment by margeeta** [comment]
Hi, thanks for the feedback:
We removed the color schematic some time ago. It is available in the playground file (Open in… +Playground File) from the figma community page https://www.figma.com/community/plugin/1034969338659738588/material-theme-builder

Colors will generate in styles and variables.
