### ISSUE TITLE
Font values differ to Kotlin

### ISSUE THREAD

**Issue by tonyhallett** [material-foundation/material-theme-builder#35]
**Describe the bug**
The Typography generated by material theme builder ( and exported ) disagrees with Kotlin defaults.

**To Reproduce**
1. Generate Typography
2. Check the values - for instance display large
![image](https://user-images.githubusercontent.com/11292998/153024646-28633b0c-d90d-470c-8b2b-1b556f49f36c.png)
3. Check against https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/tokens/TypeScaleTokens.kt

**Expected behavior**
Defaults agree with Kotlin defaults

display large should be -0.2
title medium should be 0.2
body medium should be 0.2

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
The m3 docs https://m3.material.io/styles/typography/tokens also disagree with Kotlin ( and the Material Design Builder ).
I have added an issue https://github.com/material-components/material-components/issues/104 but it is not in the docs site as I cannot find it.  If you aware of the docs repo then please let me know.

**Comment by rodydavis** [comment]
Thanks for the feedback! I will look into the issue.

cc @jwill

**Comment by jwill** [comment]
Removing typography from generation as Compose is pinned to earlier version than ours. Will now fallback to their version.
