### ISSUE TITLE
Export for angular-material

### ISSUE THREAD

**Issue by danitag78** [material-foundation/material-theme-builder#38]
Is it possible to add export for scss file to use with angular-material with extended colours?

**Comment by rodydavis** [comment]
I can look into adding sass/scss export!

Given the current css could you paste an example of the ideal layout?

**Comment by yegor-pelykh** [comment]
I need export for Angular Material too, as well as many other people.

**Comment by kintz09** [comment]
I'm not using Angular, but would also love to be able to export the theme to Sass (scss preferred) instead of just css. Especially if there were some useful mixins available in that export.

**Comment by Fitzchev** [comment]
I don't see any progress here despite a PR from @twerske from last year still open. Is it likely to happen?

**Comment by marc-wilson** [comment]
+1. I'm kind of shocked there's no export option for angular.

**Comment by themocs** [comment]
I think it's because they only support android development over desktop.

**Comment by margeeta** [comment]
Hey y'all, 
We decided to go with CSS export to support a wider range of instead of focusing on specific web frameworks.

**Comment by themocs** [comment]
> Hey y'all, We decided to go with CSS export to support a wider range of instead of focusing on specific web frameworks.

It's not planned support to SCSS file export? SASS it's was a great improvement over site personalization, why not make it available?

**Comment by marc-wilson** [comment]
@margeeta I understand your point, but it seems a bit contradictory. Google, the creator of the Material Design Specification, also owns Flutter and Angular. So, it would be logical to provide something tailored for Angular (you've done so for Flutter).

The purpose of the tool is to simplify theme customization and then allow easy export for integration with underlying technologies. You've achieved this for Flutter, which is understandable. Similarly, not doing so for Swift also makes sense. However, not having a similar solution for Angular is puzzling.

While there is a generic CSS file, it often requires substantial modification to work properly with the underlying application or framework. Given that Angular Material is commonly used with Angular, it would be more practical to avoid a generic CSS file for any web app (which isn’t always the case) and instead support frameworks that are inherently based on Material Design (like Angular and Flutter). Angular Material see's this css file as an anti pattern. There is a very opinionated/specific way to setup theming in order for it to work properly and follow the Material Spec to the T.

In my opinion, not supporting an Angular Material specific export is a significant oversight.

**Comment by singatias** [comment]
Reopening the issue since it was never merged. I want to point out that the current PR was submitted in may 2022.

**Comment by XhstormR** [comment]
+1
