### ISSUE TITLE
Add support to create elevation styles also in figma

### ISSUE THREAD

**Issue by beingminimal** [material-foundation/material-theme-builder#4]
**Is your feature request related to a problem? Please describe.**
Currently figma plugin supports only creating text and color styles.
But elevation styles are also required to work with material design V3.

**Describe the solution you'd like**
Plugin should ask to generate elevation styles also for light and dark both themes and which should optional also.
So user can create elevation styles as per their requirement.

**Describe alternatives you've considered**
Currently these styles are available in M3 Figma kit file only but not supported in plugin.

**Additional context**

**Comment by rodydavis** [comment]
Could you share some examples of elevation styles you would need?

**Comment by codecycleteam** [comment]
@rodydavis As shown in this page as surface tones https://m3.material.io/styles/color/the-color-system/color-roles#0abbf8b7-61e1-49ee-9f97-4967beb1e4fe
And it's also there in this design kit https://www.figma.com/community/file/1035203688168086460

If plugin can generate this according to theme so designer can work closely with material theme v3 specs.
So please add this feature in plugin, so on generation of new theme via plugin will also create elevation styles in figma which will help designers to iterate faster in design. 

Let me know if any other efforts required from my side.
Thanks

**Comment by DamonGuzman** [comment]
Any update on this?
