### ISSUE TITLE
Material Theme Builder Web - Export Android Views - custom color values same for unharmonized and harmonized

### ISSUE THREAD

**Issue by tonyhallett** [material-foundation/material-theme-builder#41]
**Describe the bug**
Export - Android Views has the same style item values in themes.xml for custom color regardless of whether checked "Harmonize" or not.

**To Reproduce**
1. Go to https://material-foundation.github.io/material-theme-builder/#/custom
2. Click on 'Add a Color'
3. Add a custom color - e.g 183, 115, 48 
4. Export / Android Views
5. Check Harmonize
6. Export / Android Views
7. Compare the values - they are the same.

**Expected behavior**
They should be different.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version 98.0.4758.102 (Official Build) (64-bit)

**Additional context**
The values exported agree with the unharmonized values from copying the values directly from the webpage.
Assuming that this is correct ( I have yet to calculate myself with the harmonize function ) then you are always exporting the unharmonized values despite `<item name="harmonizeColor99">true</item>`

[material-theme.zip](https://github.com/material-foundation/material-theme-builder/files/8141656/material-theme.zip)
[material-theme-uh.zip](https://github.com/material-foundation/material-theme-builder/files/8141658/material-theme-uh.zip)

**Comment by jwill** [comment]
The value exported will always be the source color because we have to support runtime harmonization.

See https://codelabs.developers.google.com/harmonize-color-android-views#6 and the MaterialColors class for more info. 

Closing issue.

**Comment by jwill** [comment]
The value exported will always be the source color because we have to support runtime harmonization.

See https://codelabs.developers.google.com/harmonize-color-android-views#6 and the MaterialColors class for more info. 

Closing issue.
