### ISSUE TITLE
Hi, Why does importing DSP not work?

### ISSUE THREAD

**Issue by lijxse** [material-foundation/material-theme-builder#43]
Hi, I exported the DSP file from the website, but when I import it into Theme Builder it does not work.

And the second question: Why there is no "Harmonized" function for custom colors in Figma plugin?

I like this feature, but it's not in the Figma plugin, which is why I need to import Figma from the website.

https://user-images.githubusercontent.com/20184046/155912020-6d4f9976-6496-452f-acdb-90222931aa6c.mp4

**Comment by kartik1225** [comment]
It's still not working! Did anyone find any workaround?

**Comment by SyedAhkam** [comment]
It's the same for me. Additionally, I can't even set colors by myself in custom tab.

**Comment by lastnameisgold** [comment]
This is still not working. What's the point of having the option to import a DSP file but it doesn't do anything? 🙃

**Comment by goodgoodstudydaydayupyeah** [comment]
not working!

**Comment by andrewperry** [comment]
I guess they 'fixed it' by removing the import option... seems that the export in DSP format has also been removed!?
