### ISSUE TITLE
Crush during theme creation

### ISSUE THREAD

**Issue by vkharapaev** [material-foundation/material-theme-builder#45]

**Comment by vkharapaev** [comment]
https://user-images.githubusercontent.com/69600124/159811930-b6091a7e-f1a8-4fc8-94d3-7cf3e3293348.mp4

**Comment by vkharapaev** [comment]
https://youtu.be/Pbdwpbal6jU

**Comment by vkharapaev** [comment]
https://youtu.be/Pbdwpbal6jU

![Videos](https://user-images.githubusercontent.com/69600124/159814472-eb7f048d-b7c0-40a2-bfd8-67e73c48d995.jpg)

**Comment by margeeta** [comment]
Fixed in updates
