### ISSUE TITLE
Add support to create grid styles also in figma

### ISSUE THREAD

**Issue by beingminimal** [material-foundation/material-theme-builder#5]
**Is your feature request related to a problem? Please describe.**
Currently figma plugin supports only creating text and color styles.
But grid styles are also required to work with material design V3.

**Describe the solution you'd like**
Plugin should ask to generate grid styles also, and which should optional also.
So user can create grid styles as per their requirement.

**Describe alternatives you've considered**
Currently grid styles are available in M3 Figma kit file only but not supported in plugin.

**Additional context**

**Comment by rodydavis** [comment]
What kind of grid styles would you want?

Could you provide some examples?

**Comment by codecycleteam** [comment]
@rodydavis Add support in plugin to generate grid styles also supported by M3 specs & it's also there in material design kit please check here https://www.figma.com/community/file/1035203688168086460

Thank You

**Comment by margeeta** [comment]
Thanks! We'll add this as a feature request, but the M3 Design Kit should be used for grid styles as they are not a theme attribute.
