### ISSUE TITLE
Material Theme Builder Not Working

### ISSUE THREAD

**Issue by 13arraza** [material-foundation/material-theme-builder#52]
**Describe the bug**
The plugin does not create anything other than a Text object, text styles and color styles (does not produce the color palette with uploaded picture beside it).

**To Reproduce**
1. Open the Material Theme Builder Plugin
2. Click on 'Dynamic' tab
3. Upload a photo (in this screenshot is 'download.png')
4. Wait for loading
5. See error (does not create color palette with the uploaded photo beside it)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [99.0.4844.84]

**Smartphone (please complete the following information):**

**Additional context**
The first 4 photos are the steps taken to produce the error
5th and 6th photos are the text instance created after I upload 'download.png' (or any picture) on dynamic tab in the plugin
The photo I tried to use for the plugin (which is 'download.png') will be included as the last picture
What I have tried to fix the problem:
1.Reinstall Material Theme Builder plugin
2.Reinstall Figma
3.Delete files from AppData/Roaming/Figma and AppData/Roaming/FigmaAgent before reinstalling

![step1](https://user-images.githubusercontent.com/36200815/161686954-353ab29b-73a2-4619-ac17-5ff62b0d99af.PNG)
![step2](https://user-images.githubusercontent.com/36200815/161687031-7b468d52-af4a-46ec-954b-eeacaa93f28c.PNG)
![step3](https://user-images.githubusercontent.com/36200815/161687215-f9a4a02c-9324-45fa-975f-1fac43b8365e.PNG)
![step4](https://user-images.githubusercontent.com/36200815/161687243-db6ced7a-9201-4b82-8bf3-90a3c472cdb0.PNG)
![step5](https://user-images.githubusercontent.com/36200815/161687557-ecc3f638-1be9-4556-be38-da08aa966c56.PNG)
![step6](https://user-images.githubusercontent.com/36200815/161687699-cdee11ad-acdb-424d-9682-892cd17b49e0.PNG)
![download](https://user-images.githubusercontent.com/36200815/161687845-c6829d7f-6070-4b90-b38d-7d7358cc11f5.png)

**Comment by rodydavis** [comment]
Thank you for the great feedback, I have tracked down the issue: https://github.com/material-foundation/material-theme-builder/issues/57

Change is being applied and rolling out!
