### ISSUE TITLE
Exported Theme for Jetpack Compose is faulty

### ISSUE THREAD

**Issue by djnotes** [material-foundation/material-theme-builder#56]
**Describe the bug**
Exported code for Compose code does not compile. Lots of missing imports in Theme.kt and some types do not resolve to anything. 

**To Reproduce**
1. Go to 'https://material-foundation.github.io/material-theme-builder/#/custom'
2. Click 'Export' after making some changes or as is. 
3. Select Jetpack Compose (Theme.kt)
4. Extract files and copy the three files Theme, Color, and Type(.kt) to `your-package`.m3
5. Rename the package address at the top of the files to your package. 
6. There are lots of red lines in Theme.kt

**Expected behavior**
There should be no errors and the required compoents should have already been imported in the file. 

**Screenshots**
![Screenshot from 2022-04-11 14-30-17](https://user-images.githubusercontent.com/9320387/162805860-125698b6-ac1d-4536-a322-4193da6b754f.png)
safari]

**Desktop (please complete the following information):**
 - OS: Linux  Fedora 35

**Additional context**
I'm running Android Studio Chipmunk 2021.2.1 Beta 4. 

androidx.compose.material3*, androidx.compose.material*, and com.google.android.material* has been added to dependencies.

**Comment by fuomag9** [comment]
Also some variables are straight missing or should not even be there?
![image](https://user-images.githubusercontent.com/1580624/164975579-e99e1675-0d57-4235-ad46-46efc008e5df.png)

**Comment by CmdrSharp** [comment]
@rodydavis What're the odds you've had a chance to look at this? :)

**Comment by jwill** [comment]
Harmonization on Compose was meant to be a beta feature and not exported all the time, I'm in the midst of a migration so I can't roll a quick fix.

You can safely delete everything from  `data class CustomColor` until the end of the file.

**Comment by ArbenMaloku** [comment]
+1

**Comment by jwill** [comment]
Fixed in recent build.
