### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by lloydrichards** [material-foundation/material-theme-builder#57]
Am trying to use the Material Theme Builder plugin for Figma and every time I open the plugin, it crashes.  There is no message or anything, just closes.

**Comment by rodydavis** [comment]
I have discovered the bug! There was a change recently to figma causing all the plugins to crash.

```js
figma.loadFontAsync({ family: "Inter", style: "Regular" })
```

This line is needed to be added when the plugin opens. The plugin was working correctly and something changed on how nodes are updated on the canvas when no font is detected.

**Comment by rodydavis** [comment]
Fix is being applied and a new change will roll out soon.
