### ISSUE TITLE
primary colour is changed

### ISSUE THREAD

**Issue by bpappin** [material-foundation/material-theme-builder#58]
**Describe the bug**
When you input a specific custom colour for your Primary, Secondary or Tertiary, the tool *changes* that colour to something else.

This happens in both the web version and the Figma version.

**To Reproduce**
1. Go to the Figmal plugin, or Web tool
2. Click on "Primary" and change the colour to hex value #002949, and apply that.
3. Check the value of the primary colour, it will have been changed to #0061A3.
4. The value of the primary colour was changed from #002949 to #0061A3.

**Expected behavior**
The tool *should not* change a custom colour when its directly specified.

**Additional context**
This happens in both the web version, and the Figma version.

**Comment by aisgbnok** [comment]
I believe I'm having a similar issue, possibly related? The system generates a secondary color from the primary color, if I change the secondary color, and then decide to change it back I can't. It won't accept the secondary color it originally generated.

I know the rendered palette isn't supposed to match the source color, but in this instance, something seems off? I'm not sure if this is expected? You will also notice that even dismissing the input alert (clicking cancel) changes the secondary color for some reason even if nothing was changed.

https://user-images.githubusercontent.com/10838153/164592716-e418c527-1e3b-4b5a-a07c-0bf3b566d1be.mp4
I hope this helps, thank you! The Material Theme Builder is a great tool!

**Comment by jwill** [comment]
That is correct, it is currently expected behavior.
