### ISSUE TITLE
Swap button does not swap all the tokens

### ISSUE THREAD

**Issue by pbutterworth** [material-foundation/material-theme-builder#59]
**Describe the bug**
When using the 'Swap' button to change themes, not all of the tokens are swapped.

**To Reproduce**
1. Select some UI components that use a range of the colour tokens (the card example from Material 3 Design Kit for instance)
2. Note that the initial theme is 'M3'.  In the selection colors panel, all the colour styles are 'M3/...'
3. Select a different theme in the plugin, and click 'Swap'
4. Note in the selection colors panel, there is now a mixture of M3/... and [CustomTheme]/...

**Expected behavior**
All the colour tokens should be swapped over to the selected theme

**Screenshots**
<img width="616" alt="image" src="https://user-images.githubusercontent.com/3683210/164328547-1dafa542-551d-49ce-afa6-4eb050c9b9fd.png">
<img width="606" alt="image" src="https://user-images.githubusercontent.com/3683210/164328668-927b598e-3a77-43ce-9fd0-e8a07b8da61b.png">

**Desktop (please complete the following information):**
Figma Desktop App version 112.2
macOS 12.1
plugin version 9

**Comment by AnneKok** [comment]
This is still an issue, from what I can tell if you select a layer and Swap, the swap fails on any child layers that are component instances. I think that is a bug.
