### ISSUE TITLE
Inverse Primary color style missing

### ISSUE THREAD

**Issue by codecycleteam** [material-foundation/material-theme-builder#6]
**Describe the bug**
As we can see in below screenshot that on M3 website there is a mention of color "Inverse Primary" in theme generated by plugin.

**To Reproduce**
1. Generate new theme from plugin and you can crosscheck that this color is not being generated as style.

**Expected behavior**
This color style should be generated with plugin.

**Screenshots**

<img width="1105" alt="Screenshot 2021-10-29 at 5 20 30 PM" src="https://user-images.githubusercontent.com/84431724/139429930-835c0c69-8a9b-4002-a0da-906ec6bb0cb5.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rodydavis** [comment]
Thank you for the feedback!

**Comment by codecycleteam** [comment]
@rodydavis Please ping me once it's live in plugin, thank you.

**Comment by codecycleteam** [comment]
@rodydavis i know it is there in M3 docs, but that colour is not being generated as figma style by figma theme generator plugin, so i have created this issue to solve this. So let me know when it will be solves. Thanks

**Comment by rodydavis** [comment]
Inverse primary and shadow added on the latest!

**Comment by bpappin** [comment]
so is there a workaround? they dont seem to be there in the web tool

**Comment by NVLudwig** [comment]
> 

Hello @rodydavis,
I'm still not seeing inverse colours in figma Plugin nor in the web theme builder. Has this feature been abandoned and the inverse colors deprecated(no documentation on how to generate these seems available)?

**Comment by NVLudwig** [comment]
> 
Hi @bpappin, 
So On a hunch I doubled checked the Figma plugin output and realized it does not generate a frame with the inverse colors for you to see BUT the colors are in the Figma color Pallet.

![image](https://user-images.githubusercontent.com/29584087/171049562-e3761f35-e2f8-4f6d-8268-ba6a8e37ffce.png)

**Comment by rodydavis** [comment]
That is correct, it's not reflected on the diagram but they are available in styles.

The plug-in is not abandoned and is under active development.
