### ISSUE TITLE
Reopening the plugin clobbers customised Secondary and Tertiary colours

### ISSUE THREAD

**Issue by pbutterworth** [material-foundation/material-theme-builder#65]
**Describe the bug**
After creating a new theme, and customising the Secondary and Tertiary colours, reopening the pluging and switching to the Custom tab causes the secondary and tertiary colours to be clobbered back to the automatically generated colours.

**To Reproduce**
1. Create a new theme
3. Open the Custom tab
4. Change the Secondary and Tertiary colours to something other than the default generated colours
5. Close the plugin
6. Reopen the plugin
7. Switch to the Custom tab. At this moment, observed that the Secondary and Tertiary colours revert the the original default generated colours.

**Expected behavior**
The plugin should remember the customisations

**Screenshots**
First time customising the theme:
![image](https://user-images.githubusercontent.com/3683210/165879878-80f52a9c-a34f-43bd-aa4e-dc236d3a1ac6.png)

After reopening the plugin (but before switching to the custom tab:
![image](https://user-images.githubusercontent.com/3683210/165879979-991fa808-c215-4ebb-a4c1-184869970574.png)

After clicking on the Custom tab. Note that the customised colours have reverted:
![image](https://user-images.githubusercontent.com/3683210/165879960-f2e916d3-4d13-48bf-9c13-0672d125a9a4.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.1
 - Figma desktop 114.3
 - plugin version 9

**Comment by pbutterworth** [comment]
Discovered a workaround:
If you have more than one theme in the current file, after opening the plugin, choose a different theme (any one) from the drop-down, then pick the first theme again from the drop-down. This then opens the custom tab with the correct colours populated.

**Comment by xingyanbin** [comment]
> rent file, after opening the plugin, choose a different theme (any one) from the drop-down, then pick the first theme again from the drop-down. This then opens th

I had the same problem today, wish has a solution for this.

**Comment by butlerjason** [comment]
I have the same issue and without a workaround, I can't use this for our design system.
