### ISSUE TITLE
Provide Typography for all type of devices not only for desktop

### ISSUE THREAD

**Issue by beingminimal** [material-foundation/material-theme-builder#7]
**Is your feature request related to a problem? Please describe.**
Right now, M3 gives details of typography for desktop device only.
But designers required typography details for all type of devices as shown in below screeshot.

**Describe the solution you'd like**
Kindly provide detailed typography for all type of devices as shown in M3 website screenshot with newly updated categories like small, medium, large.
And with font weight, line spacing, line height, etc.

Like display medium and large font style is missing for large screen tv and similarly it required for all type of devices as shown in image.

![Screenshot 2021-10-30 at 9 28 27 AM](https://user-images.githubusercontent.com/84431724/139520386-6f8b3505-c82c-4dab-a550-a8e50dddb106.png)

**Describe alternatives you've considered**
There is no alternative.

**Additional context**

**Comment by rodydavis** [comment]
Thank you for the feedback!

**Comment by codecycleteam** [comment]
@rodydavis Any ETA for diff typography support for all type of screens in M3 specs & plungin?
