### ISSUE TITLE
Feature request: platform support

### ISSUE THREAD

**Issue by PavloGrubyi** [material-foundation/material-theme-builder#70]
Hello,

Could you add support for having multiple platforms? For example, an ability to put down platforms and switch between them?
![size-tokens@2x_1649708427916](https://user-images.githubusercontent.com/7049016/169533571-57e17876-c4c6-421b-ba85-124e844d0da6.png)

**Comment by margeeta** [comment]
For multiple platforms, you could handle in a similar fashion as multiple themes. Add a theme for each to swap between.
