### ISSUE TITLE
Exporting for Android results in wrong closing tags and colour reference

### ISSUE THREAD

**Issue by steamedham544** [material-foundation/material-theme-builder#72]
**Describe the bug**
Exporting a theme for Android results in the following bugs:
1. Colours in colors.xml have the wrong closing tag. It has `</item>`.
2. In themes.xml for both dark and light themes have a typo for referencing inversePrimary.

**To Reproduce**
1. Create a theme
2. Export to Android

**Expected behavior**
1. The closing tags in colors.xml should be `</color>` instead of `</item>`

2. Dark theme: change the colour referenced in `colorPrimaryInverse` from `@color/md_theme_dark_primaryInverse` to `@color/md_theme_dark_inversePrimary`

3. Light theme: change the colour reference in `colorPrimartInverse` from `@color/md_theme_light_primaryInverse` to `@color/md_theme_light_inversePrimary
`

**Comment by steamedham544** [comment]
@jwill there's a problem with background colours too in both themes.xml files.

It's name been set as `android:colorBackground` but it's supposed to be `backgroundColor`

**Comment by jwill** [comment]
android:colorBackground is actually correct, from the spec: https://github.com/material-components/material-components-android/blob/3fdfb6e230767138849edf858c13da1bf1d3f90b/lib/java/com/google/android/material/theme/res/values/themes_base.xml#L39

**Comment by jwill** [comment]
The other issue with closing tags was resolved in the recent build.
