### ISSUE TITLE
Downloaded XMLs after color changes are not updated until webpage refresh

### ISSUE THREAD

**Issue by tomermandelfw** [material-foundation/material-theme-builder#79]
**Describe the bug**
When exporting a theme after a previous download and color change, the downloaded XMLs are identical to the previous download. Webpage refresh fixes this issue.

**To Reproduce**
1. In Chrome browser - go to '[The Material Theme Builder](https://material-foundation.github.io/material-theme-builder/#/custom)' (Custom tab)
2. Click on 'Export' -> 'Android Views (XML)'
3. Change the colors.
5. Click on 'Export' -> 'Android Views (XML)'
6. The downloaded colors.xml is identical to the previous download before the color change (refreshing the page fixes this issue).

**Expected behavior**
The downloaded XMLs should be set to the new chosen colors.

**Comment by jwill** [comment]
Has been fixed in the most recent build
