### ISSUE TITLE
Bugs about Extended Colors

### ISSUE THREAD

**Issue by freefish1218** [material-foundation/material-theme-builder#80]
** Version 11 of Figma plugin**

Many bugs have been fixed, thanks! 

Currently found another bug:  custom color names have problems, especially after renaming the same color will appear more than one set of names, some confusion.

**Comment by margeeta** [comment]
Hi! Do you mind providing a screenshot or video of the duplication occurring and steps? 

Thanks!

**Comment by freefish1218** [comment]
> 

<img width="797" alt="image" src="https://user-images.githubusercontent.com/2015639/182124849-e794e060-be53-4ac7-ab14-54ddb038a65c.png">
