### ISSUE TITLE
Web custom theme builder ignores the specific user-entered primary colour and instead applies a different primary colour to the theme

### ISSUE THREAD

**Issue by Fando** [material-foundation/material-theme-builder#86]
The [web custom theme builder](https://m3.material.io/theme-builder#/custom) ignores the specific user-entered primary colour, and instead applies a similar, but different, primary colour to the theme.

Please add a feature that would allow the user to enter the actual primary colour and not a seed colour

**Comment by JagarYousef** [comment]
Yes and this makes the `Theme Builder` 98% useless. 
It is mostly done by a junior dev and has never be debugged by any.

**Comment by margeeta** [comment]
Hi, the color system and algorithm is always being updated based on user feedback, please keep an eye out for these changes. 
For precise color input, check out the Figma plugin, as it will export Figma style properties as is. 
Thanks!
