### ISSUE TITLE
Export doesn't work, nothing downloads

### ISSUE THREAD

**Issue by ecoant** [material-foundation/material-theme-builder#87]
**Describe the bug**
The export button fails to do anything for all export types

**To Reproduce**
1. Build a custom theme
2. Click on Export
3. Click any option for export format
4. Open inspector -> console
5. See error

**Expected behavior**
I get a downloaded file with my theme

![Screen Shot 2022-10-14 at 5 06 03 PM](https://user-images.githubusercontent.com/103153447/195950964-73d761ea-6307-4a71-97fb-9b4a006ae10f.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 106.0.5249.119 (Official Build) (arm64)

**EDIT** I'm not sure why, but nuking my browser has made this bug go away.

**Comment by ecoant** [comment]
I'm not sure why, but nuking my browser has made this bug go away.

**Comment by marlonlom** [comment]
Hey, this is still happening... same issue, this must be reopened.
