### ISSUE TITLE
Switching source colors resets all text styles

### ISSUE THREAD

**Issue by PrattiDev** [material-foundation/material-theme-builder#9]
**Describe the bug**
Changing the source color in the plugin will reset all text styles to their baseline counterparts.

**To Reproduce**
1. Open the plugin.
2. Select the Shuffle button.
3. Your text styles will have been reset.

**Expected behavior**
Text styles that have been changed should not be reset when simply changing the source color for dynamic theming.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 92.0.4515.131

![yqyeSsm9la](https://user-images.githubusercontent.com/17130024/139786939-0b2f7c88-7a4a-434e-8c7d-68baaa715a88.gif)

**Comment by rodydavis** [comment]
This is something I am hoping to improve. Currently it just works off of roboto in readonly, but I need to add a check to see if the token has been updated and not override.

I will see what I can change about the update logic!

**Comment by margeeta** [comment]
Fixed :)
