### ISSUE TITLE
Can a theme created in the Figma Material Theme Builder plugin be renamed or deleted?

### ISSUE THREAD

**Issue by kintz09** [material-foundation/material-theme-builder#90]
I've newly started using Figma with the Material Theme Builder plugin paired with the Material 3 Design Kit (Community) file to create a UI Library. I'm managing a few themes for the various products I am designing. I'd like my themes to be named for easy identification. I can do this, however, I don't love that the default theme still exists as it adds a lot of additional styles with similar names to sort through when selecting a style in Figma.

There's two solutions that immediately come to mind:

- Rename the default theme, or
- Delete the default theme

However, I haven't figured out how to do this. Can a theme be renamed or deleted?

**Comment by margeeta** [comment]
Thanks for using the theme builder and design kit!
Yes, themes can be renamed and deleted after being created through the Figma styles panel on the right pane. 
**To rename:** 
1. Without anything on the canvas selected, double click the style group. 
2. This will convert the group name to an input where you can rename the style group. 
3. Repeat for each corresponding style grouping (type, etc.)
4. The theme builder pulls the names from these groupings, so reopening should have the updated name within the dropdown theme menu. 

**To delete** 
Similar to renaming, within the style panel, delete the style groups. When the theme builder plugin is reopened the theme will not appear. 
![Screen Shot 2022-11-07 at 10 41 06 AM](https://user-images.githubusercontent.com/10263978/200390526-e2ea4878-ca05-4da3-ba5c-15212e0eefd2.png)
![Screen Shot 2022-11-07 at 10 43 24 AM](https://user-images.githubusercontent.com/10263978/200390541-93b64d17-4ba6-4b92-ba0f-4a9a6ea423f6.png)

**Comment by kintz09** [comment]
Ah, well that makes sense. Thanks for the quick solution!
