### ISSUE TITLE
[Web] "Add Wallpaper" not working

### ISSUE THREAD

**Issue by Ghedeon** [material-foundation/material-theme-builder#92]
**Describe the bug**
"Add Wallpaper/Wallpaper Link" actions have no effect

**To Reproduce**
1. Click on 'Add Wallpaper'
2. Select an image to upload
4. See nothing happens

**Expected behavior**
A new theme is generated out of the uploaded image

**Desktop:**
 - Browser: stock Chrome
 - Version 107.0.5304.87

**Comment by jwill** [comment]
Fixed.
