### ISSUE TITLE
[BUG] The website isn't showing anything

### ISSUE THREAD

**Issue by Zestski** [material-foundation/material-theme-builder#95]
**Describe the bug**
The website isn't working here, just show a blank page for me.

**To Reproduce**
1. Go to 'Material Design Theme Builder website'
2. Wait for the site to load completely.
3. Blank page.

**Expected behavior**
That the site would load normally.

**Screenshots**
![screen](https://user-images.githubusercontent.com/96800745/202914247-e831258d-7864-46f3-9172-458fd1c30062.jpg)

**Desktop (please complete the following information):**
 - OS: Lubuntu 22.04.1 LTS
 - Browser Chrome
 - Version 107.0.5304.87

**Comment by berkanaslan** [comment]
Same issue here!

**Comment by SkyLissh** [comment]
Same issue, seems to be an error when the app call to a javascript file.
![image](https://user-images.githubusercontent.com/72633267/202924438-e62b5d12-ca70-4d8b-816c-ae34da54752b.png)

**Comment by Zestski** [comment]
I hope this problem is resolved quickly.

**Comment by Zestski** [comment]
Seems that has been resolved, closing this issue.
