### ISSUE TITLE
Export Button on Custom M3 Builder Web page Not working

### ISSUE THREAD

**Issue by grndvl1** [material-foundation/material-theme-builder#97]
**Describe the bug**
Create a custom color palette and trying to export it to android xml click on the export button and nothing happens.
https://m3.material.io/theme-builder#/custom

**To Reproduce**
1. Go to create palette
2. Click on export and pick Android XML
3. see nothing happens and no dowload triggered or saved to download directory
4. 4. not working in both Chrome and Safari

**Expected behavior**
Should get a zip file download

**Screenshots**

**Desktop (please complete the following information):**
 - OS: latest MAc
 - Browser latest Chrome and Safari

**Comment by Salavin** [comment]
Same issue here; seems like it may be isolated to MacOS as I tried it on a Windows machine, and it worked fine.

**Comment by jwill** [comment]
It seems to come and go at random, mostly on MacOS. Sometimes download is affected by having extensions that block multiple downloads, other times it is resolved as randomly as it appears. 

Unable to duplicate at the moment. Thanks for the report.

**Comment by adsonafonso** [comment]
I've tried this on Chrome and Safari, and both times the download doesn't start for me @jwill. I'm running MacOS 14.0 and I have no extra extensions
