### ISSUE TITLE
How to download tonal pallet in colors.xml

### ISSUE THREAD

**Issue by imandaliya** [material-foundation/material-theme-builder#98]
In most of cases all colors are fulfil requirements in design, but i recently design app that require many of the colors that contains in tonal color pallet list which is described in below image. when you download theme its only contains light and dark mode color combinations but not tonal colors list.
![Screenshot 2022-12-10 at 4 18 09 PM](https://user-images.githubusercontent.com/971804/206851337-6c79b4dd-efae-4c4d-9376-78a44ffbfe07.png)

my request to add specific button that allow to download tonal color pallet also. thanks

**Comment by jwill** [comment]
We don't have that planned at the moment as the intent is for designs to use the pre-specified color roles and not select individual tones from the palette but will be logging the feature request. Thanks for filing it. 

Closing as WAI/Won't Fix.
